// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        c_address0,
        c_ce0,
        c_we0,
        c_d0,
        c_q0,
        sm_address0,
        sm_ce0,
        sm_q0,
        sm_address1,
        sm_ce1,
        sm_q1
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] c_address0;
output   c_ce0;
output   c_we0;
output  [31:0] c_d0;
input  [31:0] c_q0;
output  [12:0] sm_address0;
output   sm_ce0;
input  [7:0] sm_q0;
output  [12:0] sm_address1;
output   sm_ce1;
input  [7:0] sm_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] c_address0;
reg c_ce0;
reg c_we0;
reg[31:0] c_d0;

(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] grp_keccak_absorb_1_fu_203_ap_return;
reg   [7:0] state_pos_reg_476;
wire    ap_CS_fsm_state3;
reg   [4:0] i_reg_481;
reg   [4:0] state_s_addr_7_reg_486;
wire    ap_CS_fsm_state4;
wire   [4:0] state_s_addr_8_reg_491;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln529_fu_350_p1;
reg   [63:0] zext_ln529_reg_505;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln529_fu_344_p2;
wire   [0:0] icmp_ln531_fu_354_p2;
reg   [0:0] icmp_ln531_reg_510;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state19;
wire   [31:0] pos_fu_365_p2;
wire    ap_CS_fsm_state20;
reg   [7:0] c_addr_reg_527;
wire   [0:0] icmp_ln537_fu_375_p2;
reg   [7:0] buf_address0;
reg    buf_ce0;
reg    buf_we0;
reg   [7:0] buf_d0;
wire   [7:0] buf_q0;
reg   [7:0] buf_address1;
reg    buf_ce1;
reg    buf_we1;
reg   [7:0] buf_d1;
reg   [4:0] state_s_address0;
reg    state_s_ce0;
reg    state_s_we0;
reg   [63:0] state_s_d0;
wire   [63:0] state_s_q0;
reg   [4:0] state_s_address1;
reg    state_s_ce1;
reg    state_s_we1;
reg   [63:0] state_s_d1;
wire   [63:0] state_s_q1;
wire    grp_keccak_absorb_1_fu_203_ap_start;
wire    grp_keccak_absorb_1_fu_203_ap_done;
wire    grp_keccak_absorb_1_fu_203_ap_idle;
wire    grp_keccak_absorb_1_fu_203_ap_ready;
wire   [4:0] grp_keccak_absorb_1_fu_203_s_address0;
wire    grp_keccak_absorb_1_fu_203_s_ce0;
wire    grp_keccak_absorb_1_fu_203_s_we0;
wire   [63:0] grp_keccak_absorb_1_fu_203_s_d0;
wire   [4:0] grp_keccak_absorb_1_fu_203_s_address1;
wire    grp_keccak_absorb_1_fu_203_s_ce1;
wire    grp_keccak_absorb_1_fu_203_s_we1;
wire   [63:0] grp_keccak_absorb_1_fu_203_s_d1;
wire   [12:0] grp_keccak_absorb_1_fu_203_sm_address0;
wire    grp_keccak_absorb_1_fu_203_sm_ce0;
wire   [12:0] grp_keccak_absorb_1_fu_203_sm_address1;
wire    grp_keccak_absorb_1_fu_203_sm_ce1;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_start;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_done;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_idle;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_ready;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_address0;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_ce0;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_we0;
wire   [31:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_d0;
wire    grp_KeccakF1600_StatePermute_fu_224_ap_start;
wire    grp_KeccakF1600_StatePermute_fu_224_ap_done;
wire    grp_KeccakF1600_StatePermute_fu_224_ap_idle;
wire    grp_KeccakF1600_StatePermute_fu_224_ap_ready;
wire   [4:0] grp_KeccakF1600_StatePermute_fu_224_state_address0;
wire    grp_KeccakF1600_StatePermute_fu_224_state_ce0;
wire    grp_KeccakF1600_StatePermute_fu_224_state_we0;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_224_state_d0;
wire   [4:0] grp_KeccakF1600_StatePermute_fu_224_state_address1;
wire    grp_KeccakF1600_StatePermute_fu_224_state_ce1;
wire    grp_KeccakF1600_StatePermute_fu_224_state_we1;
wire   [63:0] grp_KeccakF1600_StatePermute_fu_224_state_d1;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_start;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_done;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_idle;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_ready;
wire   [4:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_state_s_address0;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_state_s_ce0;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_address0;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_ce0;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_we0;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_d0;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_address1;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_ce1;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_we1;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_d1;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_start;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_done;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_idle;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_ready;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_buf_r_address0;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_buf_r_ce0;
wire   [63:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_signs_out_o;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_signs_out_o_ap_vld;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_start;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_done;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_idle;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_ready;
wire   [4:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_state_s_address0;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_state_s_ce0;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_address0;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_ce0;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_we0;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_d0;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_address1;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_ce1;
wire    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_we1;
wire   [7:0] grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_d1;
reg   [31:0] pos_1_reg_180;
reg   [31:0] pos_2_reg_190;
wire    ap_CS_fsm_state18;
reg    ap_block_state18_on_subcall_done;
reg    grp_keccak_absorb_1_fu_203_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln362_fu_262_p2;
reg    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_start_reg;
reg    grp_KeccakF1600_StatePermute_fu_224_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state16;
reg    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg   [63:0] signs_fu_106;
reg    grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_start_reg;
wire    ap_CS_fsm_state17;
wire   [63:0] zext_ln362_fu_257_p1;
wire   [63:0] zext_ln450_6_fu_299_p1;
wire   [63:0] zext_ln536_fu_360_p1;
wire   [63:0] zext_ln537_fu_380_p1;
wire    ap_CS_fsm_state21;
reg   [4:0] i_47_fu_94;
wire   [4:0] add_ln362_fu_268_p2;
wire   [63:0] zext_ln541_fu_436_p1;
wire    ap_CS_fsm_state22;
reg   [8:0] i_48_fu_110;
wire   [8:0] add_ln529_fu_385_p2;
reg   [31:0] pos_02_fu_114;
wire    ap_CS_fsm_state5;
wire   [63:0] xor_ln450_fu_324_p2;
wire    ap_CS_fsm_state7;
wire   [63:0] xor_ln451_fu_331_p2;
wire  signed [31:0] sext_ln540_fu_421_p1;
wire   [2:0] trunc_ln450_fu_303_p1;
wire   [5:0] shl_ln_fu_306_p3;
wire   [63:0] zext_ln450_fu_314_p1;
wire   [63:0] shl_ln450_fu_318_p2;
wire   [8:0] zext_ln537_1_fu_371_p1;
wire   [0:0] trunc_ln540_fu_403_p1;
wire   [1:0] shl_ln1_fu_407_p3;
wire   [1:0] sub_ln540_fu_415_p2;
wire   [62:0] signs_1_fu_426_p4;
reg   [21:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
#0 grp_keccak_absorb_1_fu_203_ap_start_reg = 1'b0;
#0 grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_start_reg = 1'b0;
#0 grp_KeccakF1600_StatePermute_fu_224_ap_start_reg = 1'b0;
#0 grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_start_reg = 1'b0;
#0 grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_start_reg = 1'b0;
#0 grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_start_reg = 1'b0;
end

pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_buf_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 136 ),
    .AddressWidth( 8 ))
buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_address0),
    .ce0(buf_ce0),
    .we0(buf_we0),
    .d0(buf_d0),
    .q0(buf_q0),
    .address1(buf_address1),
    .ce1(buf_ce1),
    .we1(buf_we1),
    .d1(buf_d1)
);

pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_state_s_RAM_AUTO_1R1W #(
    .DataWidth( 64 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
state_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(state_s_address0),
    .ce0(state_s_ce0),
    .we0(state_s_we0),
    .d0(state_s_d0),
    .q0(state_s_q0),
    .address1(state_s_address1),
    .ce1(state_s_ce1),
    .we1(state_s_we1),
    .d1(state_s_d1),
    .q1(state_s_q1)
);

pqcrystals_dilithium2_ref_keccak_absorb_1 grp_keccak_absorb_1_fu_203(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_keccak_absorb_1_fu_203_ap_start),
    .ap_done(grp_keccak_absorb_1_fu_203_ap_done),
    .ap_idle(grp_keccak_absorb_1_fu_203_ap_idle),
    .ap_ready(grp_keccak_absorb_1_fu_203_ap_ready),
    .s_address0(grp_keccak_absorb_1_fu_203_s_address0),
    .s_ce0(grp_keccak_absorb_1_fu_203_s_ce0),
    .s_we0(grp_keccak_absorb_1_fu_203_s_we0),
    .s_d0(grp_keccak_absorb_1_fu_203_s_d0),
    .s_q0(state_s_q0),
    .s_address1(grp_keccak_absorb_1_fu_203_s_address1),
    .s_ce1(grp_keccak_absorb_1_fu_203_s_ce1),
    .s_we1(grp_keccak_absorb_1_fu_203_s_we1),
    .s_d1(grp_keccak_absorb_1_fu_203_s_d1),
    .s_q1(state_s_q1),
    .pos_offset(5'd0),
    .sm_address0(grp_keccak_absorb_1_fu_203_sm_address0),
    .sm_ce0(grp_keccak_absorb_1_fu_203_sm_ce0),
    .sm_q0(sm_q0),
    .sm_address1(grp_keccak_absorb_1_fu_203_sm_address1),
    .sm_ce1(grp_keccak_absorb_1_fu_203_sm_ce1),
    .sm_q1(sm_q1),
    .m_offset(12'd0),
    .mlen_offset(64'd32),
    .ap_return(grp_keccak_absorb_1_fu_203_ap_return)
);

pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2 grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_start),
    .ap_done(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_done),
    .ap_idle(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_idle),
    .ap_ready(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_ready),
    .c_address0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_address0),
    .c_ce0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_ce0),
    .c_we0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_we0),
    .c_d0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_d0)
);

pqcrystals_dilithium2_ref_KeccakF1600_StatePermute grp_KeccakF1600_StatePermute_fu_224(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_KeccakF1600_StatePermute_fu_224_ap_start),
    .ap_done(grp_KeccakF1600_StatePermute_fu_224_ap_done),
    .ap_idle(grp_KeccakF1600_StatePermute_fu_224_ap_idle),
    .ap_ready(grp_KeccakF1600_StatePermute_fu_224_ap_ready),
    .state_address0(grp_KeccakF1600_StatePermute_fu_224_state_address0),
    .state_ce0(grp_KeccakF1600_StatePermute_fu_224_state_ce0),
    .state_we0(grp_KeccakF1600_StatePermute_fu_224_state_we0),
    .state_d0(grp_KeccakF1600_StatePermute_fu_224_state_d0),
    .state_q0(state_s_q0),
    .state_address1(grp_KeccakF1600_StatePermute_fu_224_state_address1),
    .state_ce1(grp_KeccakF1600_StatePermute_fu_224_state_ce1),
    .state_we1(grp_KeccakF1600_StatePermute_fu_224_state_we1),
    .state_d1(grp_KeccakF1600_StatePermute_fu_224_state_d1),
    .state_q1(state_s_q1)
);

pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2 grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_start),
    .ap_done(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_done),
    .ap_idle(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_idle),
    .ap_ready(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_ready),
    .state_s_address0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_state_s_address0),
    .state_s_ce0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_state_s_ce0),
    .state_s_q0(state_s_q0),
    .buf_r_address0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_address0),
    .buf_r_ce0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_ce0),
    .buf_r_we0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_we0),
    .buf_r_d0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_d0),
    .buf_r_address1(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_address1),
    .buf_r_ce1(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_ce1),
    .buf_r_we1(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_we1),
    .buf_r_d1(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_d1)
);

pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1 grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_start),
    .ap_done(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_done),
    .ap_idle(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_idle),
    .ap_ready(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_ready),
    .buf_r_address0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_buf_r_address0),
    .buf_r_ce0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_buf_r_ce0),
    .buf_r_q0(buf_q0),
    .signs_out_i(signs_fu_106),
    .signs_out_o(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_signs_out_o),
    .signs_out_o_ap_vld(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_signs_out_o_ap_vld)
);

pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223 grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_start),
    .ap_done(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_done),
    .ap_idle(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_idle),
    .ap_ready(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_ready),
    .state_s_address0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_state_s_address0),
    .state_s_ce0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_state_s_ce0),
    .state_s_q0(state_s_q0),
    .buf_r_address0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_address0),
    .buf_r_ce0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_ce0),
    .buf_r_we0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_we0),
    .buf_r_d0(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_d0),
    .buf_r_address1(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_address1),
    .buf_r_ce1(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_ce1),
    .buf_r_we1(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_we1),
    .buf_r_d1(grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_KeccakF1600_StatePermute_fu_224_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) | ((icmp_ln531_fu_354_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15)))) begin
            grp_KeccakF1600_StatePermute_fu_224_ap_start_reg <= 1'b1;
        end else if ((grp_KeccakF1600_StatePermute_fu_224_ap_ready == 1'b1)) begin
            grp_KeccakF1600_StatePermute_fu_224_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_keccak_absorb_1_fu_203_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln362_fu_262_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_keccak_absorb_1_fu_203_ap_start_reg <= 1'b1;
        end else if ((grp_keccak_absorb_1_fu_203_ap_ready == 1'b1)) begin
            grp_keccak_absorb_1_fu_203_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_start_reg <= 1'b1;
        end else if ((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_ready == 1'b1)) begin
            grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_start_reg <= 1'b1;
        end else if ((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_ready == 1'b1)) begin
            grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_start_reg <= 1'b1;
        end else if ((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_ready == 1'b1)) begin
            grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln362_fu_262_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_ready == 1'b1)) begin
            grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_47_fu_94 <= 5'd0;
    end else if (((icmp_ln362_fu_262_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_47_fu_94 <= add_ln362_fu_268_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln362_fu_262_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_48_fu_110 <= 9'd217;
    end else if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln537_fu_375_p2 == 1'd0))) begin
        i_48_fu_110 <= add_ln529_fu_385_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln362_fu_262_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        pos_02_fu_114 <= 32'd8;
    end else if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln537_fu_375_p2 == 1'd0))) begin
        pos_02_fu_114 <= pos_fu_365_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln537_fu_375_p2 == 1'd1))) begin
        pos_1_reg_180 <= pos_fu_365_p2;
    end else if (((icmp_ln529_fu_344_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        pos_1_reg_180 <= pos_02_fu_114;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln531_fu_354_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
        pos_2_reg_190 <= pos_1_reg_180;
    end else if (((icmp_ln531_reg_510 == 1'd1) & (1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
        pos_2_reg_190 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        signs_fu_106 <= zext_ln541_fu_436_p1;
    end else if (((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_signs_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        signs_fu_106 <= grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_signs_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln537_fu_375_p2 == 1'd0))) begin
        c_addr_reg_527 <= zext_ln537_fu_380_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_481 <= {{grp_keccak_absorb_1_fu_203_ap_return[7:3]}};
        state_pos_reg_476 <= grp_keccak_absorb_1_fu_203_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        icmp_ln531_reg_510 <= icmp_ln531_fu_354_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        state_s_addr_7_reg_486 <= zext_ln450_6_fu_299_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln529_fu_344_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state14))) begin
        zext_ln529_reg_505[8 : 0] <= zext_ln529_fu_350_p1[8 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_KeccakF1600_StatePermute_fu_224_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state18_on_subcall_done)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_KeccakF1600_StatePermute_fu_224_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln529_fu_344_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln529_fu_344_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        buf_address0 = zext_ln536_fu_360_p1;
    end else if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_address0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        buf_address0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_address0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_address0;
    end else begin
        buf_address0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_address1 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_address1 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_address1;
    end else begin
        buf_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        buf_ce0 = 1'b1;
    end else if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_ce0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        buf_ce0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_ce0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_ce0;
    end else begin
        buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_ce1 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_ce1 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_ce1;
    end else begin
        buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_d0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_d0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_d0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_d0;
    end else begin
        buf_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_d1 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_d1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_d1 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_d1;
    end else begin
        buf_d1 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_we0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_we0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_we0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_we0;
    end else begin
        buf_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        buf_we1 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_buf_r_we1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        buf_we1 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_buf_r_we1;
    end else begin
        buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        c_address0 = c_addr_reg_527;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        c_address0 = zext_ln529_reg_505;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        c_address0 = zext_ln537_fu_380_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        c_address0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_address0;
    end else begin
        c_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        c_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        c_ce0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_ce0;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        c_d0 = sext_ln540_fu_421_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        c_d0 = c_q0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        c_d0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_d0;
    end else begin
        c_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21))) begin
        c_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        c_we0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_c_we0;
    end else begin
        c_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        state_s_address0 = state_s_addr_8_reg_491;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        state_s_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        state_s_address0 = state_s_addr_7_reg_486;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        state_s_address0 = zext_ln450_6_fu_299_p1;
    end else if (((icmp_ln362_fu_262_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        state_s_address0 = zext_ln362_fu_257_p1;
    end else if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        state_s_address0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_state_s_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        state_s_address0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_state_s_address0;
    end else if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9))) begin
        state_s_address0 = grp_KeccakF1600_StatePermute_fu_224_state_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_s_address0 = grp_keccak_absorb_1_fu_203_s_address0;
    end else begin
        state_s_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9))) begin
        state_s_address1 = grp_KeccakF1600_StatePermute_fu_224_state_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_s_address1 = grp_keccak_absorb_1_fu_203_s_address1;
    end else begin
        state_s_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | ((icmp_ln362_fu_262_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        state_s_ce0 = 1'b1;
    end else if (((icmp_ln531_reg_510 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        state_s_ce0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_state_s_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        state_s_ce0 = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_state_s_ce0;
    end else if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9))) begin
        state_s_ce0 = grp_KeccakF1600_StatePermute_fu_224_state_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_s_ce0 = grp_keccak_absorb_1_fu_203_s_ce0;
    end else begin
        state_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9))) begin
        state_s_ce1 = grp_KeccakF1600_StatePermute_fu_224_state_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_s_ce1 = grp_keccak_absorb_1_fu_203_s_ce1;
    end else begin
        state_s_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        state_s_d0 = xor_ln451_fu_331_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        state_s_d0 = xor_ln450_fu_324_p2;
    end else if (((icmp_ln362_fu_262_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        state_s_d0 = 64'd0;
    end else if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9))) begin
        state_s_d0 = grp_KeccakF1600_StatePermute_fu_224_state_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_s_d0 = grp_keccak_absorb_1_fu_203_s_d0;
    end else begin
        state_s_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9))) begin
        state_s_d1 = grp_KeccakF1600_StatePermute_fu_224_state_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_s_d1 = grp_keccak_absorb_1_fu_203_s_d1;
    end else begin
        state_s_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state5) | ((icmp_ln362_fu_262_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        state_s_we0 = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9))) begin
        state_s_we0 = grp_KeccakF1600_StatePermute_fu_224_state_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_s_we0 = grp_keccak_absorb_1_fu_203_s_we0;
    end else begin
        state_s_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9))) begin
        state_s_we1 = grp_KeccakF1600_StatePermute_fu_224_state_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        state_s_we1 = grp_keccak_absorb_1_fu_203_s_we1;
    end else begin
        state_s_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln362_fu_262_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_CS_fsm_state9) & (grp_KeccakF1600_StatePermute_fu_224_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((icmp_ln529_fu_344_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln531_fu_354_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (grp_KeccakF1600_StatePermute_fu_224_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b0 == ap_block_state18_on_subcall_done) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((1'b1 == ap_CS_fsm_state20) & (icmp_ln537_fu_375_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln362_fu_268_p2 = (i_47_fu_94 + 5'd1);

assign add_ln529_fu_385_p2 = (i_48_fu_110 + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state18_on_subcall_done = ((icmp_ln531_reg_510 == 1'd1) & (grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_done == 1'b0) | (grp_keccak_absorb_1_fu_203_ap_done == 1'b0));
end

assign grp_KeccakF1600_StatePermute_fu_224_ap_start = grp_KeccakF1600_StatePermute_fu_224_ap_start_reg;

assign grp_keccak_absorb_1_fu_203_ap_start = grp_keccak_absorb_1_fu_203_ap_start_reg;

assign grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_start = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223_fu_243_ap_start_reg;

assign grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_start = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2_fu_231_ap_start_reg;

assign grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_start = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1_fu_237_ap_start_reg;

assign grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_start = grp_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2_fu_218_ap_start_reg;

assign icmp_ln362_fu_262_p2 = ((i_47_fu_94 == 5'd25) ? 1'b1 : 1'b0);

assign icmp_ln529_fu_344_p2 = ((i_48_fu_110 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln531_fu_354_p2 = ((pos_1_reg_180 > 32'd135) ? 1'b1 : 1'b0);

assign icmp_ln537_fu_375_p2 = ((i_48_fu_110 < zext_ln537_1_fu_371_p1) ? 1'b1 : 1'b0);

assign pos_fu_365_p2 = (pos_2_reg_190 + 32'd1);

assign sext_ln540_fu_421_p1 = $signed(sub_ln540_fu_415_p2);

assign shl_ln1_fu_407_p3 = {{trunc_ln540_fu_403_p1}, {1'd0}};

assign shl_ln450_fu_318_p2 = 64'd31 << zext_ln450_fu_314_p1;

assign shl_ln_fu_306_p3 = {{trunc_ln450_fu_303_p1}, {3'd0}};

assign signs_1_fu_426_p4 = {{signs_fu_106[63:1]}};

assign sm_address0 = grp_keccak_absorb_1_fu_203_sm_address0;

assign sm_address1 = grp_keccak_absorb_1_fu_203_sm_address1;

assign sm_ce0 = grp_keccak_absorb_1_fu_203_sm_ce0;

assign sm_ce1 = grp_keccak_absorb_1_fu_203_sm_ce1;

assign state_s_addr_8_reg_491 = 64'd16;

assign sub_ln540_fu_415_p2 = (2'd1 - shl_ln1_fu_407_p3);

assign trunc_ln450_fu_303_p1 = state_pos_reg_476[2:0];

assign trunc_ln540_fu_403_p1 = signs_fu_106[0:0];

assign xor_ln450_fu_324_p2 = (state_s_q0 ^ shl_ln450_fu_318_p2);

assign xor_ln451_fu_331_p2 = (state_s_q0 ^ 64'd9223372036854775808);

assign zext_ln362_fu_257_p1 = i_47_fu_94;

assign zext_ln450_6_fu_299_p1 = i_reg_481;

assign zext_ln450_fu_314_p1 = shl_ln_fu_306_p3;

assign zext_ln529_fu_350_p1 = i_48_fu_110;

assign zext_ln536_fu_360_p1 = pos_2_reg_190;

assign zext_ln537_1_fu_371_p1 = buf_q0;

assign zext_ln537_fu_380_p1 = buf_q0;

assign zext_ln541_fu_436_p1 = signs_1_fu_426_p4;

always @ (posedge ap_clk) begin
    zext_ln529_reg_505[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1
