set SynModuleInfo {
  {SRCNAME pqcrystals_dilithium2_ref_Pipeline_VITIS_LOOP_205_1 MODELNAME pqcrystals_dilithium2_ref_Pipeline_VITIS_LOOP_205_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_Pipeline_VITIS_LOOP_205_1
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_flow_control_loop_pipe_sequential_init RTLNAME pqcrystals_dilithium2_ref_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME pqcrystals_dilithium2_ref_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_122_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_122_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_122_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_126_2 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_126_2 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_126_2}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_130_3 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_130_3 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_130_3}
  {SRCNAME pqcrystals_dilithium2_ref_polyeta_unpack.1 MODELNAME pqcrystals_dilithium2_ref_polyeta_unpack_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_polyeta_unpack_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_134_4 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_134_4 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_134_4}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_138_5 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_138_5 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_138_5}
  {SRCNAME pqcrystals_dilithium2_ref_polyt0_unpack.1 MODELNAME pqcrystals_dilithium2_ref_polyt0_unpack_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_polyt0_unpack_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_142_6 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_142_6 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_142_6}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_362_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_362_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_362_1}
  {SRCNAME keccak_absorb.19 MODELNAME keccak_absorb_19 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_19}
  {SRCNAME keccak_absorb.1_Pipeline_VITIS_LOOP_391_1 MODELNAME keccak_absorb_1_Pipeline_VITIS_LOOP_391_1 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1_Pipeline_VITIS_LOOP_391_1}
  {SRCNAME keccak_absorb.1_Pipeline_VITIS_LOOP_30_1 MODELNAME keccak_absorb_1_Pipeline_VITIS_LOOP_30_1 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1_Pipeline_VITIS_LOOP_30_1}
  {SRCNAME keccak_absorb.1_Pipeline_VITIS_LOOP_400_2 MODELNAME keccak_absorb_1_Pipeline_VITIS_LOOP_400_2 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1_Pipeline_VITIS_LOOP_400_2}
  {SRCNAME KeccakF1600_StatePermute MODELNAME KeccakF1600_StatePermute RTLNAME pqcrystals_dilithium2_ref_KeccakF1600_StatePermute
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_KeccakF1600_StatePermute_KeccakF_RoundConstants_ROM_AUTO_1R RTLNAME pqcrystals_dilithium2_ref_KeccakF1600_StatePermute_KeccakF_RoundConstants_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME keccak_absorb.1_Pipeline_VITIS_LOOP_409_4 MODELNAME keccak_absorb_1_Pipeline_VITIS_LOOP_409_4 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1_Pipeline_VITIS_LOOP_409_4}
  {SRCNAME keccak_absorb.1_Pipeline_VITIS_LOOP_416_5 MODELNAME keccak_absorb_1_Pipeline_VITIS_LOOP_416_5 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1_Pipeline_VITIS_LOOP_416_5}
  {SRCNAME keccak_absorb.1_Pipeline_VITIS_LOOP_423_6 MODELNAME keccak_absorb_1_Pipeline_VITIS_LOOP_423_6 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1_Pipeline_VITIS_LOOP_423_6}
  {SRCNAME keccak_absorb.1_Pipeline_VITIS_LOOP_425_7 MODELNAME keccak_absorb_1_Pipeline_VITIS_LOOP_425_7 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1_Pipeline_VITIS_LOOP_425_7}
  {SRCNAME keccak_absorb.1_Pipeline_VITIS_LOOP_30_124 MODELNAME keccak_absorb_1_Pipeline_VITIS_LOOP_30_124 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1_Pipeline_VITIS_LOOP_30_124}
  {SRCNAME keccak_absorb.1 MODELNAME keccak_absorb_1 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_keccak_absorb_1_t_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_1_t_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_540_5 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_540_5 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_540_5}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_362_18 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_362_18 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_362_18}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_416_5 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_416_5 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_416_5}
  {SRCNAME KeccakF1600_StatePermute.1 MODELNAME KeccakF1600_StatePermute_1 RTLNAME pqcrystals_dilithium2_ref_KeccakF1600_StatePermute_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_540_59 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_540_59 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_540_59}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_416_5 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_416_5 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_416_5}
  {SRCNAME keccak_absorb_Pipeline_VITIS_LOOP_391_1 MODELNAME keccak_absorb_Pipeline_VITIS_LOOP_391_1 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_Pipeline_VITIS_LOOP_391_1}
  {SRCNAME keccak_absorb_Pipeline_VITIS_LOOP_30_1 MODELNAME keccak_absorb_Pipeline_VITIS_LOOP_30_1 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_Pipeline_VITIS_LOOP_30_1}
  {SRCNAME keccak_absorb_Pipeline_VITIS_LOOP_400_2 MODELNAME keccak_absorb_Pipeline_VITIS_LOOP_400_2 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_Pipeline_VITIS_LOOP_400_2}
  {SRCNAME keccak_absorb_Pipeline_VITIS_LOOP_409_4 MODELNAME keccak_absorb_Pipeline_VITIS_LOOP_409_4 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_Pipeline_VITIS_LOOP_409_4}
  {SRCNAME keccak_absorb_Pipeline_VITIS_LOOP_416_5 MODELNAME keccak_absorb_Pipeline_VITIS_LOOP_416_5 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_Pipeline_VITIS_LOOP_416_5}
  {SRCNAME keccak_absorb_Pipeline_VITIS_LOOP_423_6 MODELNAME keccak_absorb_Pipeline_VITIS_LOOP_423_6 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_Pipeline_VITIS_LOOP_423_6}
  {SRCNAME keccak_absorb_Pipeline_VITIS_LOOP_425_7 MODELNAME keccak_absorb_Pipeline_VITIS_LOOP_425_7 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_Pipeline_VITIS_LOOP_425_7}
  {SRCNAME keccak_absorb_Pipeline_VITIS_LOOP_30_125 MODELNAME keccak_absorb_Pipeline_VITIS_LOOP_30_125 RTLNAME pqcrystals_dilithium2_ref_keccak_absorb_Pipeline_VITIS_LOOP_30_125}
  {SRCNAME keccak_absorb MODELNAME keccak_absorb RTLNAME pqcrystals_dilithium2_ref_keccak_absorb}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_476_2 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_476_2 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_476_2}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_337_1 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_337_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_337_1}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_379_2 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_379_2 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_379_2}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_476_221 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_476_221 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_476_221}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_337_122 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_337_122 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_Pipeline_VITIS_LOOP_337_122}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform MODELNAME pqcrystals_dilithium2_ref_poly_uniform RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_urem_10s_3ns_9_14_seq_1 RTLNAME pqcrystals_dilithium2_ref_urem_10s_3ns_9_14_seq_1 BINDTYPE op TYPE urem IMPL auto_seq LATENCY 13 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_buf_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_buf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_state_s_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_state_s_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_57_3 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_3 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_3
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_mul_32s_23s_54_1_1 RTLNAME pqcrystals_dilithium2_ref_mul_32s_23s_54_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_mul_32s_27ns_32_1_1 RTLNAME pqcrystals_dilithium2_ref_mul_32s_27ns_32_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_mul_32s_24s_55_1_1 RTLNAME pqcrystals_dilithium2_ref_mul_32s_24s_55_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_57_310 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_310 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_310}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_57_311 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_311 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_311}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_gamma1_Pipeline_VITIS_LOOP_416_5 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_gamma1_Pipeline_VITIS_LOOP_416_5 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_gamma1_Pipeline_VITIS_LOOP_416_5}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_gamma1_Pipeline_VITIS_LOOP_476_2 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_gamma1_Pipeline_VITIS_LOOP_476_2 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_gamma1_Pipeline_VITIS_LOOP_476_2}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_gamma1_Pipeline_VITIS_LOOP_854_1 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_gamma1_Pipeline_VITIS_LOOP_854_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_gamma1_Pipeline_VITIS_LOOP_854_1}
  {SRCNAME pqcrystals_dilithium2_ref_poly_uniform_gamma1 MODELNAME pqcrystals_dilithium2_ref_poly_uniform_gamma1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_gamma1
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_gamma1_buf_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_uniform_gamma1_buf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_57_312 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_312 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_312}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_180_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_180_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_180_1
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_mul_32s_23ns_55_1_1 RTLNAME pqcrystals_dilithium2_ref_mul_32s_23ns_55_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_180_113 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_180_113 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_180_113}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_87_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_87_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_87_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_187_1_VITIS_LOOP_32_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_187_1_VITIS_LOOP_32_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_187_1_VITIS_LOOP_32_1
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_mac_muladd_9s_24s_32ns_32_4_1 RTLNAME pqcrystals_dilithium2_ref_mac_muladd_9s_24s_32ns_32_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_polyveck_invntt_tomont_Pipeline_VITIS_LOOP_86_3 MODELNAME pqcrystals_dilithium2_ref_polyveck_invntt_tomont_Pipeline_VITIS_LOOP_86_3 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_polyveck_invntt_tomont_Pipeline_VITIS_LOOP_86_3}
  {SRCNAME pqcrystals_dilithium2_ref_polyveck_invntt_tomont_Pipeline_VITIS_LOOP_95_4 MODELNAME pqcrystals_dilithium2_ref_polyveck_invntt_tomont_Pipeline_VITIS_LOOP_95_4 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_polyveck_invntt_tomont_Pipeline_VITIS_LOOP_95_4
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_mul_32s_17ns_49_1_1 RTLNAME pqcrystals_dilithium2_ref_mul_32s_17ns_49_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_polyveck_invntt_tomont MODELNAME pqcrystals_dilithium2_ref_polyveck_invntt_tomont RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_polyveck_invntt_tomont}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_50_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_50_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_50_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_371_1_VITIS_LOOP_225_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_371_1_VITIS_LOOP_225_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_371_1_VITIS_LOOP_225_1
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_mac_muladd_25s_14ns_24ns_32_4_1 RTLNAME pqcrystals_dilithium2_ref_mac_muladd_25s_14ns_24ns_32_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_mac_muladd_8s_19s_32s_32_4_1 RTLNAME pqcrystals_dilithium2_ref_mac_muladd_8s_19s_32s_32_4_1 BINDTYPE op TYPE all IMPL dsp48 LATENCY 3 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_418_1_VITIS_LOOP_915_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_418_1_VITIS_LOOP_915_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_418_1_VITIS_LOOP_915_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_362_114 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_362_114 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_362_114}
  {SRCNAME keccak_squeeze.1 MODELNAME keccak_squeeze_1 RTLNAME pqcrystals_dilithium2_ref_keccak_squeeze_1}
  {SRCNAME pqcrystals_dilithium2_ref_poly_challenge.1_Pipeline_VITIS_LOOP_476_2 MODELNAME pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_2}
  {SRCNAME pqcrystals_dilithium2_ref_poly_challenge.1_Pipeline_VITIS_LOOP_523_1 MODELNAME pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_523_1}
  {SRCNAME pqcrystals_dilithium2_ref_poly_challenge.1_Pipeline_VITIS_LOOP_527_2 MODELNAME pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_527_2}
  {SRCNAME pqcrystals_dilithium2_ref_poly_challenge.1_Pipeline_VITIS_LOOP_476_223 MODELNAME pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_Pipeline_VITIS_LOOP_476_223}
  {SRCNAME pqcrystals_dilithium2_ref_poly_challenge.1 MODELNAME pqcrystals_dilithium2_ref_poly_challenge_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_buf_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_poly_challenge_1_buf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_57_315 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_315 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_57_315}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_114_1_VITIS_LOOP_180_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_114_1_VITIS_LOOP_180_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_114_1_VITIS_LOOP_180_1
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_mul_32s_32s_64_1_1 RTLNAME pqcrystals_dilithium2_ref_mul_32s_32s_64_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_86_3 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_86_3 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_86_3}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_95_4 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_95_4 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_95_4}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_85_1_VITIS_LOOP_87_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_85_1_VITIS_LOOP_87_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_85_1_VITIS_LOOP_87_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_53_1_VITIS_LOOP_32_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_53_1_VITIS_LOOP_32_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_53_1_VITIS_LOOP_32_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_158_1_VITIS_LOOP_298_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_158_1_VITIS_LOOP_298_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_158_1_VITIS_LOOP_298_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_305_1_VITIS_LOOP_180_1.1.1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_305_1_VITIS_LOOP_180_1_1_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_305_1_VITIS_LOOP_180_1_1_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_252_1_VITIS_LOOP_108_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_252_1_VITIS_LOOP_108_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_252_1_VITIS_LOOP_108_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_187_1_VITIS_LOOP_32_11.1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_187_1_VITIS_LOOP_32_11_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_187_1_VITIS_LOOP_32_11_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_298_1.1.1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_298_1_1_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_298_1_1_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_305_1_VITIS_LOOP_180_1.1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_305_1_VITIS_LOOP_180_1_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_305_1_VITIS_LOOP_180_1_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_187_1_VITIS_LOOP_32_11 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_187_1_VITIS_LOOP_32_11 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_187_1_VITIS_LOOP_32_11}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_298_1.1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_298_1_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_325_1_VITIS_LOOP_298_1_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_234_1_VITIS_LOOP_87_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_234_1_VITIS_LOOP_87_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_234_1_VITIS_LOOP_87_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_50_12 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_50_12 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_202_1_VITIS_LOOP_50_12}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1_Pipeline_VITIS_LOOP_392_1_VITIS_LOOP_248_1 MODELNAME pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_392_1_VITIS_LOOP_248_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_Pipeline_VITIS_LOOP_392_1_VITIS_LOOP_248_1}
  {SRCNAME pqcrystals_dilithium2_ref_pack_sig.1_Pipeline_VITIS_LOOP_167_2_VITIS_LOOP_804_1 MODELNAME pqcrystals_dilithium2_ref_pack_sig_1_Pipeline_VITIS_LOOP_167_2_VITIS_LOOP_804_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_pack_sig_1_Pipeline_VITIS_LOOP_167_2_VITIS_LOOP_804_1}
  {SRCNAME pqcrystals_dilithium2_ref_pack_sig.1_Pipeline_VITIS_LOOP_172_3 MODELNAME pqcrystals_dilithium2_ref_pack_sig_1_Pipeline_VITIS_LOOP_172_3 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_pack_sig_1_Pipeline_VITIS_LOOP_172_3}
  {SRCNAME pqcrystals_dilithium2_ref_pack_sig.1_Pipeline_VITIS_LOOP_176_4_VITIS_LOOP_177_5 MODELNAME pqcrystals_dilithium2_ref_pack_sig_1_Pipeline_VITIS_LOOP_176_4_VITIS_LOOP_177_5 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_pack_sig_1_Pipeline_VITIS_LOOP_176_4_VITIS_LOOP_177_5}
  {SRCNAME pqcrystals_dilithium2_ref_pack_sig.1 MODELNAME pqcrystals_dilithium2_ref_pack_sig_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_pack_sig_1}
  {SRCNAME pqcrystals_dilithium2_ref_signature.1 MODELNAME pqcrystals_dilithium2_ref_signature_1 RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1
    SUBMODULES {
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_zetas_ROM_AUTO_1R RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_zetas_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_t_coeffs_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_t_coeffs_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_seedbuf_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_seedbuf_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_mat_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_mat_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_s1_vec_coeffs_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_s1_vec_coeffs_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_y_vec_coeffs_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_y_vec_coeffs_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_w1_vec_coeffs_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_w1_vec_coeffs_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_cp_coeffs_RAM_AUTO_1R1W RTLNAME pqcrystals_dilithium2_ref_pqcrystals_dilithium2_ref_signature_1_cp_coeffs_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME pqcrystals_dilithium2_ref MODELNAME pqcrystals_dilithium2_ref RTLNAME pqcrystals_dilithium2_ref IS_TOP 1}
}
