// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pqcrystals_dilithium_12.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pqcrystals_dilithium_12::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pqcrystals_dilithium_12::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state1 = "1";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state2 = "10";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state3 = "100";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state4 = "1000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state5 = "10000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state6 = "100000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state7 = "1000000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state8 = "10000000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state9 = "100000000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state10 = "1000000000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state11 = "10000000000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state12 = "100000000000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<15> pqcrystals_dilithium_12::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_A = "1010";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_B = "1011";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_C = "1100";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_D = "1101";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_1 = "1";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_4 = "100";
const sc_lv<1> pqcrystals_dilithium_12::ap_const_lv1_0 = "0";
const sc_lv<1> pqcrystals_dilithium_12::ap_const_lv1_1 = "1";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_5 = "101";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_9 = "1001";
const sc_lv<3> pqcrystals_dilithium_12::ap_const_lv3_5 = "101";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_0 = "0000000000";
const sc_lv<5> pqcrystals_dilithium_12::ap_const_lv5_0 = "00000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_3 = "11";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_8 = "1000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_E = "1110";
const sc_lv<7> pqcrystals_dilithium_12::ap_const_lv7_0 = "0000000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_2 = "10";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_6 = "110";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_7 = "111";
const sc_lv<3> pqcrystals_dilithium_12::ap_const_lv3_0 = "000";
const sc_lv<5> pqcrystals_dilithium_12::ap_const_lv5_11 = "10001";
const sc_lv<5> pqcrystals_dilithium_12::ap_const_lv5_1 = "1";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_88 = "10001000";
const sc_lv<3> pqcrystals_dilithium_12::ap_const_lv3_7 = "111";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_F = "1111";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_1 = "1";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_10 = "10000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_17 = "10111";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_18 = "11000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_1F = "11111";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_20 = "100000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_27 = "100111";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_28 = "101000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_2F = "101111";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_30 = "110000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_37 = "110111";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_38 = "111000";
const sc_lv<32> pqcrystals_dilithium_12::ap_const_lv32_3F = "111111";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_2 = "10";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_3 = "11";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_4 = "100";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_5 = "101";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_6 = "110";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_7 = "111";
const sc_lv<7> pqcrystals_dilithium_12::ap_const_lv7_40 = "1000000";
const sc_lv<7> pqcrystals_dilithium_12::ap_const_lv7_1 = "1";
const sc_lv<2> pqcrystals_dilithium_12::ap_const_lv2_0 = "00";
const sc_lv<19> pqcrystals_dilithium_12::ap_const_lv19_20000 = "100000000000000000";
const sc_lv<8> pqcrystals_dilithium_12::ap_const_lv8_1 = "1";
const sc_lv<6> pqcrystals_dilithium_12::ap_const_lv6_0 = "000000";
const sc_lv<8> pqcrystals_dilithium_12::ap_const_lv8_2 = "10";
const sc_lv<4> pqcrystals_dilithium_12::ap_const_lv4_0 = "0000";
const sc_lv<10> pqcrystals_dilithium_12::ap_const_lv10_8 = "1000";
const sc_lv<8> pqcrystals_dilithium_12::ap_const_lv8_3 = "11";
const bool pqcrystals_dilithium_12::ap_const_boolean_1 = true;

pqcrystals_dilithium_12::pqcrystals_dilithium_12(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buf_U = new pqcrystals_dilithibs("buf_U");
    buf_U->clk(ap_clk);
    buf_U->reset(ap_rst);
    buf_U->address0(buf_address0);
    buf_U->ce0(buf_ce0);
    buf_U->we0(buf_we0);
    buf_U->d0(buf_d0);
    buf_U->q0(buf_q0);
    buf_U->address1(buf_address1);
    buf_U->ce1(buf_ce1);
    buf_U->we1(buf_we1);
    buf_U->d1(buf_d1);
    buf_U->q1(buf_q1);
    state_s_U = new shake256_state_0_s("state_s_U");
    state_s_U->clk(ap_clk);
    state_s_U->reset(ap_rst);
    state_s_U->address0(state_s_address0);
    state_s_U->ce0(state_s_ce0);
    state_s_U->we0(state_s_we0);
    state_s_U->d0(state_s_d0);
    state_s_U->q0(state_s_q0);
    state_s_U->address1(state_s_address1);
    state_s_U->ce1(state_s_ce1);
    state_s_U->we1(state_s_we1);
    state_s_U->d1(state_s_d1);
    state_s_U->q1(state_s_q1);
    grp_KeccakF1600_StatePer_1_fu_399 = new KeccakF1600_StatePer_1("grp_KeccakF1600_StatePer_1_fu_399");
    grp_KeccakF1600_StatePer_1_fu_399->ap_clk(ap_clk);
    grp_KeccakF1600_StatePer_1_fu_399->ap_rst(ap_rst);
    grp_KeccakF1600_StatePer_1_fu_399->ap_start(grp_KeccakF1600_StatePer_1_fu_399_ap_start);
    grp_KeccakF1600_StatePer_1_fu_399->ap_done(grp_KeccakF1600_StatePer_1_fu_399_ap_done);
    grp_KeccakF1600_StatePer_1_fu_399->ap_idle(grp_KeccakF1600_StatePer_1_fu_399_ap_idle);
    grp_KeccakF1600_StatePer_1_fu_399->ap_ready(grp_KeccakF1600_StatePer_1_fu_399_ap_ready);
    grp_KeccakF1600_StatePer_1_fu_399->state_address0(grp_KeccakF1600_StatePer_1_fu_399_state_address0);
    grp_KeccakF1600_StatePer_1_fu_399->state_ce0(grp_KeccakF1600_StatePer_1_fu_399_state_ce0);
    grp_KeccakF1600_StatePer_1_fu_399->state_we0(grp_KeccakF1600_StatePer_1_fu_399_state_we0);
    grp_KeccakF1600_StatePer_1_fu_399->state_d0(grp_KeccakF1600_StatePer_1_fu_399_state_d0);
    grp_KeccakF1600_StatePer_1_fu_399->state_q0(state_s_q0);
    grp_KeccakF1600_StatePer_1_fu_399->state_address1(grp_KeccakF1600_StatePer_1_fu_399_state_address1);
    grp_KeccakF1600_StatePer_1_fu_399->state_ce1(grp_KeccakF1600_StatePer_1_fu_399_state_ce1);
    grp_KeccakF1600_StatePer_1_fu_399->state_we1(grp_KeccakF1600_StatePer_1_fu_399_state_we1);
    grp_KeccakF1600_StatePer_1_fu_399->state_d1(grp_KeccakF1600_StatePer_1_fu_399_state_d1);
    grp_KeccakF1600_StatePer_1_fu_399->state_q1(state_s_q1);
    grp_pqcrystals_dilithium_22_fu_406 = new pqcrystals_dilithium_22("grp_pqcrystals_dilithium_22_fu_406");
    grp_pqcrystals_dilithium_22_fu_406->ap_clk(ap_clk);
    grp_pqcrystals_dilithium_22_fu_406->ap_rst(ap_rst);
    grp_pqcrystals_dilithium_22_fu_406->ap_start(grp_pqcrystals_dilithium_22_fu_406_ap_start);
    grp_pqcrystals_dilithium_22_fu_406->ap_done(grp_pqcrystals_dilithium_22_fu_406_ap_done);
    grp_pqcrystals_dilithium_22_fu_406->ap_idle(grp_pqcrystals_dilithium_22_fu_406_ap_idle);
    grp_pqcrystals_dilithium_22_fu_406->ap_ready(grp_pqcrystals_dilithium_22_fu_406_ap_ready);
    grp_pqcrystals_dilithium_22_fu_406->state_s_address0(grp_pqcrystals_dilithium_22_fu_406_state_s_address0);
    grp_pqcrystals_dilithium_22_fu_406->state_s_ce0(grp_pqcrystals_dilithium_22_fu_406_state_s_ce0);
    grp_pqcrystals_dilithium_22_fu_406->state_s_we0(grp_pqcrystals_dilithium_22_fu_406_state_s_we0);
    grp_pqcrystals_dilithium_22_fu_406->state_s_d0(grp_pqcrystals_dilithium_22_fu_406_state_s_d0);
    grp_pqcrystals_dilithium_22_fu_406->state_s_q0(state_s_q0);
    grp_pqcrystals_dilithium_22_fu_406->state_s_address1(grp_pqcrystals_dilithium_22_fu_406_state_s_address1);
    grp_pqcrystals_dilithium_22_fu_406->state_s_ce1(grp_pqcrystals_dilithium_22_fu_406_state_s_ce1);
    grp_pqcrystals_dilithium_22_fu_406->state_s_we1(grp_pqcrystals_dilithium_22_fu_406_state_s_we1);
    grp_pqcrystals_dilithium_22_fu_406->state_s_d1(grp_pqcrystals_dilithium_22_fu_406_state_s_d1);
    grp_pqcrystals_dilithium_22_fu_406->state_s_q1(state_s_q1);
    grp_pqcrystals_dilithium_22_fu_406->seed_address0(grp_pqcrystals_dilithium_22_fu_406_seed_address0);
    grp_pqcrystals_dilithium_22_fu_406->seed_ce0(grp_pqcrystals_dilithium_22_fu_406_seed_ce0);
    grp_pqcrystals_dilithium_22_fu_406->seed_q0(seed_q0);
    grp_pqcrystals_dilithium_22_fu_406->seed_address1(grp_pqcrystals_dilithium_22_fu_406_seed_address1);
    grp_pqcrystals_dilithium_22_fu_406->seed_ce1(grp_pqcrystals_dilithium_22_fu_406_seed_ce1);
    grp_pqcrystals_dilithium_22_fu_406->seed_q1(seed_q1);
    grp_pqcrystals_dilithium_22_fu_406->nonce(nonce);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_coeffs_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( zext_ln855_2_fu_694_p1 );
    sensitive << ( zext_ln860_2_fu_778_p1 );
    sensitive << ( zext_ln865_1_fu_874_p1 );
    sensitive << ( zext_ln870_1_fu_970_p1 );

    SC_METHOD(thread_a_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_a_coeffs_d0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( sub_ln875_fu_737_p2 );
    sensitive << ( sub_ln876_fu_841_p2 );
    sensitive << ( sub_ln877_fu_937_p2 );
    sensitive << ( sub_ln878_fu_1009_p2 );

    SC_METHOD(thread_a_coeffs_we0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_add_ln477_fu_450_p2);
    sensitive << ( p_0_rec_i_i_reg_365 );
    sensitive << ( zext_ln477_fu_446_p1 );

    SC_METHOD(thread_add_ln478_fu_461_p2);
    sensitive << ( p_0_rec_i_i_reg_365 );

    SC_METHOD(thread_add_ln479_fu_467_p2);
    sensitive << ( p_01_i_i_reg_353 );

    SC_METHOD(thread_add_ln855_fu_655_p2);
    sensitive << ( zext_ln855_fu_651_p1 );
    sensitive << ( zext_ln854_fu_623_p1 );

    SC_METHOD(thread_add_ln856_fu_666_p2);
    sensitive << ( add_ln855_reg_1111 );

    SC_METHOD(thread_add_ln857_fu_676_p2);
    sensitive << ( add_ln855_reg_1111 );

    SC_METHOD(thread_add_ln861_fu_717_p2);
    sensitive << ( add_ln855_reg_1111 );

    SC_METHOD(thread_add_ln862_fu_727_p2);
    sensitive << ( add_ln855_reg_1111 );

    SC_METHOD(thread_add_ln866_fu_821_p2);
    sensitive << ( add_ln855_reg_1111 );

    SC_METHOD(thread_add_ln867_fu_831_p2);
    sensitive << ( add_ln855_reg_1111 );

    SC_METHOD(thread_add_ln871_fu_917_p2);
    sensitive << ( add_ln855_reg_1111 );

    SC_METHOD(thread_add_ln872_fu_927_p2);
    sensitive << ( add_ln855_reg_1111 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln854_fu_627_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln854_fu_627_p2 );

    SC_METHOD(thread_buf_address0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln477_2_fu_473_p1 );
    sensitive << ( zext_ln48_1_fu_568_p1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln48_3_fu_588_p1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln48_5_fu_608_p1 );
    sensitive << ( zext_ln855_1_fu_661_p1 );
    sensitive << ( zext_ln857_fu_681_p1 );
    sensitive << ( zext_ln862_fu_732_p1 );
    sensitive << ( zext_ln867_fu_836_p1 );
    sensitive << ( zext_ln872_fu_932_p1 );

    SC_METHOD(thread_buf_address1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln48_fu_498_p1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln48_2_fu_578_p1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln48_4_fu_598_p1 );
    sensitive << ( zext_ln48_6_fu_618_p1 );
    sensitive << ( zext_ln856_fu_671_p1 );
    sensitive << ( zext_ln861_fu_722_p1 );
    sensitive << ( zext_ln866_fu_826_p1 );
    sensitive << ( zext_ln871_fu_922_p1 );

    SC_METHOD(thread_buf_ce0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_buf_ce1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_buf_d0);
    sensitive << ( trunc_ln48_2_reg_1067 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln48_4_reg_1077 );
    sensitive << ( trunc_ln48_6_reg_1087 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( trunc_ln48_fu_477_p1 );

    SC_METHOD(thread_buf_d1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln48_3_reg_1072 );
    sensitive << ( trunc_ln48_5_reg_1082 );
    sensitive << ( trunc_ln48_7_reg_1092 );
    sensitive << ( state_s_q0 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_buf_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_buf_we1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_KeccakF1600_StatePer_1_fu_399_ap_start);
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_ap_start_reg );

    SC_METHOD(thread_grp_pqcrystals_dilithium_22_fu_406_ap_start);
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_ap_start_reg );

    SC_METHOD(thread_i_23_fu_432_p2);
    sensitive << ( i_0_i_i_reg_377 );

    SC_METHOD(thread_i_fu_633_p2);
    sensitive << ( i_0_i_reg_388 );

    SC_METHOD(thread_icmp_ln474_fu_420_p2);
    sensitive << ( p_01_i_i_reg_353 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln476_fu_426_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i_0_i_i_reg_377 );

    SC_METHOD(thread_icmp_ln854_fu_627_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( i_0_i_reg_388 );

    SC_METHOD(thread_lshr_ln1_fu_848_p4);
    sensitive << ( reg_416 );

    SC_METHOD(thread_lshr_ln2_fu_944_p4);
    sensitive << ( reg_416 );

    SC_METHOD(thread_lshr_ln_fu_751_p4);
    sensitive << ( reg_416 );

    SC_METHOD(thread_or_ln48_1_fu_563_p2);
    sensitive << ( add_ln477_reg_1040 );

    SC_METHOD(thread_or_ln48_2_fu_573_p2);
    sensitive << ( add_ln477_reg_1040 );

    SC_METHOD(thread_or_ln48_3_fu_583_p2);
    sensitive << ( add_ln477_reg_1040 );

    SC_METHOD(thread_or_ln48_4_fu_593_p2);
    sensitive << ( add_ln477_reg_1040 );

    SC_METHOD(thread_or_ln48_5_fu_603_p2);
    sensitive << ( add_ln477_reg_1040 );

    SC_METHOD(thread_or_ln48_6_fu_613_p2);
    sensitive << ( add_ln477_reg_1040 );

    SC_METHOD(thread_or_ln48_fu_493_p2);
    sensitive << ( add_ln477_reg_1040 );

    SC_METHOD(thread_or_ln860_fu_765_p2);
    sensitive << ( shl_ln855_1_fu_744_p3 );

    SC_METHOD(thread_or_ln863_fu_803_p2);
    sensitive << ( tmp_12_fu_795_p3 );
    sensitive << ( shl_ln6_fu_783_p3 );

    SC_METHOD(thread_or_ln863_i_fu_809_p3);
    sensitive << ( trunc_ln863_fu_791_p1 );
    sensitive << ( or_ln863_fu_803_p2 );

    SC_METHOD(thread_or_ln865_fu_862_p2);
    sensitive << ( shl_ln855_1_reg_1148 );

    SC_METHOD(thread_or_ln868_fu_899_p2);
    sensitive << ( tmp_14_fu_891_p3 );
    sensitive << ( shl_ln7_fu_879_p3 );

    SC_METHOD(thread_or_ln868_i_fu_905_p3);
    sensitive << ( trunc_ln868_fu_887_p1 );
    sensitive << ( or_ln868_fu_899_p2 );

    SC_METHOD(thread_or_ln870_fu_958_p2);
    sensitive << ( shl_ln855_1_reg_1148 );

    SC_METHOD(thread_or_ln872_fu_991_p2);
    sensitive << ( tmp_15_fu_983_p3 );
    sensitive << ( shl_ln8_fu_975_p3 );

    SC_METHOD(thread_or_ln872_i_fu_997_p3);
    sensitive << ( buf_q0 );
    sensitive << ( or_ln872_fu_991_p2 );

    SC_METHOD(thread_seed_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_seed_address0 );

    SC_METHOD(thread_seed_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_seed_address1 );

    SC_METHOD(thread_seed_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_seed_ce0 );

    SC_METHOD(thread_seed_ce1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_seed_ce1 );

    SC_METHOD(thread_shl_ln6_fu_783_p3);
    sensitive << ( buf_q1 );

    SC_METHOD(thread_shl_ln7_fu_879_p3);
    sensitive << ( buf_q1 );

    SC_METHOD(thread_shl_ln855_1_fu_744_p3);
    sensitive << ( trunc_ln855_reg_1105 );

    SC_METHOD(thread_shl_ln8_fu_975_p3);
    sensitive << ( buf_q1 );

    SC_METHOD(thread_shl_ln9_fu_438_p3);
    sensitive << ( i_0_i_i_reg_377 );

    SC_METHOD(thread_shl_ln_fu_643_p3);
    sensitive << ( trunc_ln855_fu_639_p1 );

    SC_METHOD(thread_state_s_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_state_address0 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_state_s_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln477_1_fu_456_p1 );

    SC_METHOD(thread_state_s_address1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_state_address1 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_state_s_address1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_s_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_state_ce0 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_state_s_ce0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_s_ce1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_state_ce1 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_state_s_ce1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_s_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_state_d0 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_state_s_d0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_s_d1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_state_d1 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_state_s_d1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_s_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_state_we0 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_state_s_we0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_state_s_we1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_state_we1 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_state_s_we1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sub_ln875_fu_737_p2);
    sensitive << ( zext_ln860_fu_713_p1 );

    SC_METHOD(thread_sub_ln876_fu_841_p2);
    sensitive << ( zext_ln863_fu_817_p1 );

    SC_METHOD(thread_sub_ln877_fu_937_p2);
    sensitive << ( zext_ln868_fu_913_p1 );

    SC_METHOD(thread_sub_ln878_fu_1009_p2);
    sensitive << ( zext_ln872_1_fu_1005_p1 );

    SC_METHOD(thread_tmp_12_fu_795_p3);
    sensitive << ( zext_ln860_1_fu_761_p1 );

    SC_METHOD(thread_tmp_14_fu_891_p3);
    sensitive << ( zext_ln865_fu_858_p1 );

    SC_METHOD(thread_tmp_15_fu_983_p3);
    sensitive << ( zext_ln870_fu_954_p1 );

    SC_METHOD(thread_tmp_517_fu_771_p3);
    sensitive << ( a_coeffs_offset );
    sensitive << ( or_ln860_fu_765_p2 );

    SC_METHOD(thread_tmp_518_fu_867_p3);
    sensitive << ( a_coeffs_offset );
    sensitive << ( or_ln865_fu_862_p2 );

    SC_METHOD(thread_tmp_519_fu_963_p3);
    sensitive << ( a_coeffs_offset );
    sensitive << ( or_ln870_fu_958_p2 );

    SC_METHOD(thread_tmp_i_fu_703_p4);
    sensitive << ( reg_416 );
    sensitive << ( buf_q1 );
    sensitive << ( trunc_ln858_fu_699_p1 );

    SC_METHOD(thread_tmp_s_fu_686_p4);
    sensitive << ( a_coeffs_offset );
    sensitive << ( trunc_ln855_reg_1105 );

    SC_METHOD(thread_trunc_ln48_fu_477_p1);
    sensitive << ( state_s_q0 );

    SC_METHOD(thread_trunc_ln855_fu_639_p1);
    sensitive << ( i_0_i_reg_388 );

    SC_METHOD(thread_trunc_ln858_fu_699_p1);
    sensitive << ( buf_q0 );

    SC_METHOD(thread_trunc_ln863_fu_791_p1);
    sensitive << ( buf_q0 );

    SC_METHOD(thread_trunc_ln868_fu_887_p1);
    sensitive << ( buf_q0 );

    SC_METHOD(thread_zext_ln477_1_fu_456_p1);
    sensitive << ( i_0_i_i_reg_377 );

    SC_METHOD(thread_zext_ln477_2_fu_473_p1);
    sensitive << ( add_ln477_reg_1040 );

    SC_METHOD(thread_zext_ln477_fu_446_p1);
    sensitive << ( shl_ln9_fu_438_p3 );

    SC_METHOD(thread_zext_ln48_1_fu_568_p1);
    sensitive << ( or_ln48_1_fu_563_p2 );

    SC_METHOD(thread_zext_ln48_2_fu_578_p1);
    sensitive << ( or_ln48_2_fu_573_p2 );

    SC_METHOD(thread_zext_ln48_3_fu_588_p1);
    sensitive << ( or_ln48_3_fu_583_p2 );

    SC_METHOD(thread_zext_ln48_4_fu_598_p1);
    sensitive << ( or_ln48_4_fu_593_p2 );

    SC_METHOD(thread_zext_ln48_5_fu_608_p1);
    sensitive << ( or_ln48_5_fu_603_p2 );

    SC_METHOD(thread_zext_ln48_6_fu_618_p1);
    sensitive << ( or_ln48_6_fu_613_p2 );

    SC_METHOD(thread_zext_ln48_fu_498_p1);
    sensitive << ( or_ln48_fu_493_p2 );

    SC_METHOD(thread_zext_ln854_fu_623_p1);
    sensitive << ( i_0_i_reg_388 );

    SC_METHOD(thread_zext_ln855_1_fu_661_p1);
    sensitive << ( add_ln855_fu_655_p2 );

    SC_METHOD(thread_zext_ln855_2_fu_694_p1);
    sensitive << ( tmp_s_fu_686_p4 );

    SC_METHOD(thread_zext_ln855_fu_651_p1);
    sensitive << ( shl_ln_fu_643_p3 );

    SC_METHOD(thread_zext_ln856_fu_671_p1);
    sensitive << ( add_ln856_fu_666_p2 );

    SC_METHOD(thread_zext_ln857_fu_681_p1);
    sensitive << ( add_ln857_fu_676_p2 );

    SC_METHOD(thread_zext_ln860_1_fu_761_p1);
    sensitive << ( lshr_ln_fu_751_p4 );

    SC_METHOD(thread_zext_ln860_2_fu_778_p1);
    sensitive << ( tmp_517_fu_771_p3 );

    SC_METHOD(thread_zext_ln860_fu_713_p1);
    sensitive << ( tmp_i_fu_703_p4 );

    SC_METHOD(thread_zext_ln861_fu_722_p1);
    sensitive << ( add_ln861_fu_717_p2 );

    SC_METHOD(thread_zext_ln862_fu_732_p1);
    sensitive << ( add_ln862_fu_727_p2 );

    SC_METHOD(thread_zext_ln863_fu_817_p1);
    sensitive << ( or_ln863_i_fu_809_p3 );

    SC_METHOD(thread_zext_ln865_1_fu_874_p1);
    sensitive << ( tmp_518_fu_867_p3 );

    SC_METHOD(thread_zext_ln865_fu_858_p1);
    sensitive << ( lshr_ln1_fu_848_p4 );

    SC_METHOD(thread_zext_ln866_fu_826_p1);
    sensitive << ( add_ln866_fu_821_p2 );

    SC_METHOD(thread_zext_ln867_fu_836_p1);
    sensitive << ( add_ln867_fu_831_p2 );

    SC_METHOD(thread_zext_ln868_fu_913_p1);
    sensitive << ( or_ln868_i_fu_905_p3 );

    SC_METHOD(thread_zext_ln870_1_fu_970_p1);
    sensitive << ( tmp_519_fu_963_p3 );

    SC_METHOD(thread_zext_ln870_fu_954_p1);
    sensitive << ( lshr_ln2_fu_944_p4 );

    SC_METHOD(thread_zext_ln871_fu_922_p1);
    sensitive << ( add_ln871_fu_917_p2 );

    SC_METHOD(thread_zext_ln872_1_fu_1005_p1);
    sensitive << ( or_ln872_i_fu_997_p3 );

    SC_METHOD(thread_zext_ln872_fu_932_p1);
    sensitive << ( add_ln872_fu_927_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( grp_pqcrystals_dilithium_22_fu_406_ap_done );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln476_fu_426_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln854_fu_627_p2 );
    sensitive << ( grp_KeccakF1600_StatePer_1_fu_399_ap_done );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln474_fu_420_p2 );

    ap_CS_fsm = "000000000000001";
    grp_KeccakF1600_StatePer_1_fu_399_ap_start_reg = SC_LOGIC_0;
    grp_pqcrystals_dilithium_22_fu_406_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pqcrystals_dilithium_12_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_coeffs_address0, "(port)a_coeffs_address0");
    sc_trace(mVcdFile, a_coeffs_ce0, "(port)a_coeffs_ce0");
    sc_trace(mVcdFile, a_coeffs_we0, "(port)a_coeffs_we0");
    sc_trace(mVcdFile, a_coeffs_d0, "(port)a_coeffs_d0");
    sc_trace(mVcdFile, a_coeffs_offset, "(port)a_coeffs_offset");
    sc_trace(mVcdFile, seed_address0, "(port)seed_address0");
    sc_trace(mVcdFile, seed_ce0, "(port)seed_ce0");
    sc_trace(mVcdFile, seed_q0, "(port)seed_q0");
    sc_trace(mVcdFile, seed_address1, "(port)seed_address1");
    sc_trace(mVcdFile, seed_ce1, "(port)seed_ce1");
    sc_trace(mVcdFile, seed_q1, "(port)seed_q1");
    sc_trace(mVcdFile, nonce, "(port)nonce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, buf_q0, "buf_q0");
    sc_trace(mVcdFile, reg_416, "reg_416");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_ap_ready, "grp_pqcrystals_dilithium_22_fu_406_ap_ready");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_ap_done, "grp_pqcrystals_dilithium_22_fu_406_ap_done");
    sc_trace(mVcdFile, i_23_fu_432_p2, "i_23_fu_432_p2");
    sc_trace(mVcdFile, i_23_reg_1035, "i_23_reg_1035");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, add_ln477_fu_450_p2, "add_ln477_fu_450_p2");
    sc_trace(mVcdFile, add_ln477_reg_1040, "add_ln477_reg_1040");
    sc_trace(mVcdFile, icmp_ln476_fu_426_p2, "icmp_ln476_fu_426_p2");
    sc_trace(mVcdFile, add_ln478_fu_461_p2, "add_ln478_fu_461_p2");
    sc_trace(mVcdFile, add_ln479_fu_467_p2, "add_ln479_fu_467_p2");
    sc_trace(mVcdFile, trunc_ln48_2_reg_1067, "trunc_ln48_2_reg_1067");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, trunc_ln48_3_reg_1072, "trunc_ln48_3_reg_1072");
    sc_trace(mVcdFile, trunc_ln48_4_reg_1077, "trunc_ln48_4_reg_1077");
    sc_trace(mVcdFile, trunc_ln48_5_reg_1082, "trunc_ln48_5_reg_1082");
    sc_trace(mVcdFile, trunc_ln48_6_reg_1087, "trunc_ln48_6_reg_1087");
    sc_trace(mVcdFile, trunc_ln48_7_reg_1092, "trunc_ln48_7_reg_1092");
    sc_trace(mVcdFile, i_fu_633_p2, "i_fu_633_p2");
    sc_trace(mVcdFile, i_reg_1100, "i_reg_1100");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, trunc_ln855_fu_639_p1, "trunc_ln855_fu_639_p1");
    sc_trace(mVcdFile, trunc_ln855_reg_1105, "trunc_ln855_reg_1105");
    sc_trace(mVcdFile, icmp_ln854_fu_627_p2, "icmp_ln854_fu_627_p2");
    sc_trace(mVcdFile, add_ln855_fu_655_p2, "add_ln855_fu_655_p2");
    sc_trace(mVcdFile, add_ln855_reg_1111, "add_ln855_reg_1111");
    sc_trace(mVcdFile, shl_ln855_1_fu_744_p3, "shl_ln855_1_fu_744_p3");
    sc_trace(mVcdFile, shl_ln855_1_reg_1148, "shl_ln855_1_reg_1148");
    sc_trace(mVcdFile, buf_address0, "buf_address0");
    sc_trace(mVcdFile, buf_ce0, "buf_ce0");
    sc_trace(mVcdFile, buf_we0, "buf_we0");
    sc_trace(mVcdFile, buf_d0, "buf_d0");
    sc_trace(mVcdFile, buf_address1, "buf_address1");
    sc_trace(mVcdFile, buf_ce1, "buf_ce1");
    sc_trace(mVcdFile, buf_we1, "buf_we1");
    sc_trace(mVcdFile, buf_d1, "buf_d1");
    sc_trace(mVcdFile, buf_q1, "buf_q1");
    sc_trace(mVcdFile, state_s_address0, "state_s_address0");
    sc_trace(mVcdFile, state_s_ce0, "state_s_ce0");
    sc_trace(mVcdFile, state_s_we0, "state_s_we0");
    sc_trace(mVcdFile, state_s_d0, "state_s_d0");
    sc_trace(mVcdFile, state_s_q0, "state_s_q0");
    sc_trace(mVcdFile, state_s_address1, "state_s_address1");
    sc_trace(mVcdFile, state_s_ce1, "state_s_ce1");
    sc_trace(mVcdFile, state_s_we1, "state_s_we1");
    sc_trace(mVcdFile, state_s_d1, "state_s_d1");
    sc_trace(mVcdFile, state_s_q1, "state_s_q1");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_ap_start, "grp_KeccakF1600_StatePer_1_fu_399_ap_start");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_ap_done, "grp_KeccakF1600_StatePer_1_fu_399_ap_done");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_ap_idle, "grp_KeccakF1600_StatePer_1_fu_399_ap_idle");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_ap_ready, "grp_KeccakF1600_StatePer_1_fu_399_ap_ready");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_state_address0, "grp_KeccakF1600_StatePer_1_fu_399_state_address0");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_state_ce0, "grp_KeccakF1600_StatePer_1_fu_399_state_ce0");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_state_we0, "grp_KeccakF1600_StatePer_1_fu_399_state_we0");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_state_d0, "grp_KeccakF1600_StatePer_1_fu_399_state_d0");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_state_address1, "grp_KeccakF1600_StatePer_1_fu_399_state_address1");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_state_ce1, "grp_KeccakF1600_StatePer_1_fu_399_state_ce1");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_state_we1, "grp_KeccakF1600_StatePer_1_fu_399_state_we1");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_state_d1, "grp_KeccakF1600_StatePer_1_fu_399_state_d1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_ap_start, "grp_pqcrystals_dilithium_22_fu_406_ap_start");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_ap_idle, "grp_pqcrystals_dilithium_22_fu_406_ap_idle");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_state_s_address0, "grp_pqcrystals_dilithium_22_fu_406_state_s_address0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_state_s_ce0, "grp_pqcrystals_dilithium_22_fu_406_state_s_ce0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_state_s_we0, "grp_pqcrystals_dilithium_22_fu_406_state_s_we0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_state_s_d0, "grp_pqcrystals_dilithium_22_fu_406_state_s_d0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_state_s_address1, "grp_pqcrystals_dilithium_22_fu_406_state_s_address1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_state_s_ce1, "grp_pqcrystals_dilithium_22_fu_406_state_s_ce1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_state_s_we1, "grp_pqcrystals_dilithium_22_fu_406_state_s_we1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_state_s_d1, "grp_pqcrystals_dilithium_22_fu_406_state_s_d1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_seed_address0, "grp_pqcrystals_dilithium_22_fu_406_seed_address0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_seed_ce0, "grp_pqcrystals_dilithium_22_fu_406_seed_ce0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_seed_address1, "grp_pqcrystals_dilithium_22_fu_406_seed_address1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_seed_ce1, "grp_pqcrystals_dilithium_22_fu_406_seed_ce1");
    sc_trace(mVcdFile, p_01_i_i_reg_353, "p_01_i_i_reg_353");
    sc_trace(mVcdFile, p_0_rec_i_i_reg_365, "p_0_rec_i_i_reg_365");
    sc_trace(mVcdFile, i_0_i_i_reg_377, "i_0_i_i_reg_377");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, i_0_i_reg_388, "i_0_i_reg_388");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln474_fu_420_p2, "icmp_ln474_fu_420_p2");
    sc_trace(mVcdFile, grp_KeccakF1600_StatePer_1_fu_399_ap_start_reg, "grp_KeccakF1600_StatePer_1_fu_399_ap_start_reg");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_22_fu_406_ap_start_reg, "grp_pqcrystals_dilithium_22_fu_406_ap_start_reg");
    sc_trace(mVcdFile, zext_ln477_1_fu_456_p1, "zext_ln477_1_fu_456_p1");
    sc_trace(mVcdFile, zext_ln477_2_fu_473_p1, "zext_ln477_2_fu_473_p1");
    sc_trace(mVcdFile, zext_ln48_fu_498_p1, "zext_ln48_fu_498_p1");
    sc_trace(mVcdFile, zext_ln48_1_fu_568_p1, "zext_ln48_1_fu_568_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, zext_ln48_2_fu_578_p1, "zext_ln48_2_fu_578_p1");
    sc_trace(mVcdFile, zext_ln48_3_fu_588_p1, "zext_ln48_3_fu_588_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, zext_ln48_4_fu_598_p1, "zext_ln48_4_fu_598_p1");
    sc_trace(mVcdFile, zext_ln48_5_fu_608_p1, "zext_ln48_5_fu_608_p1");
    sc_trace(mVcdFile, zext_ln48_6_fu_618_p1, "zext_ln48_6_fu_618_p1");
    sc_trace(mVcdFile, zext_ln855_1_fu_661_p1, "zext_ln855_1_fu_661_p1");
    sc_trace(mVcdFile, zext_ln856_fu_671_p1, "zext_ln856_fu_671_p1");
    sc_trace(mVcdFile, zext_ln857_fu_681_p1, "zext_ln857_fu_681_p1");
    sc_trace(mVcdFile, zext_ln855_2_fu_694_p1, "zext_ln855_2_fu_694_p1");
    sc_trace(mVcdFile, zext_ln861_fu_722_p1, "zext_ln861_fu_722_p1");
    sc_trace(mVcdFile, zext_ln862_fu_732_p1, "zext_ln862_fu_732_p1");
    sc_trace(mVcdFile, zext_ln860_2_fu_778_p1, "zext_ln860_2_fu_778_p1");
    sc_trace(mVcdFile, zext_ln866_fu_826_p1, "zext_ln866_fu_826_p1");
    sc_trace(mVcdFile, zext_ln867_fu_836_p1, "zext_ln867_fu_836_p1");
    sc_trace(mVcdFile, zext_ln865_1_fu_874_p1, "zext_ln865_1_fu_874_p1");
    sc_trace(mVcdFile, zext_ln871_fu_922_p1, "zext_ln871_fu_922_p1");
    sc_trace(mVcdFile, zext_ln872_fu_932_p1, "zext_ln872_fu_932_p1");
    sc_trace(mVcdFile, zext_ln870_1_fu_970_p1, "zext_ln870_1_fu_970_p1");
    sc_trace(mVcdFile, trunc_ln48_fu_477_p1, "trunc_ln48_fu_477_p1");
    sc_trace(mVcdFile, sub_ln875_fu_737_p2, "sub_ln875_fu_737_p2");
    sc_trace(mVcdFile, sub_ln876_fu_841_p2, "sub_ln876_fu_841_p2");
    sc_trace(mVcdFile, sub_ln877_fu_937_p2, "sub_ln877_fu_937_p2");
    sc_trace(mVcdFile, sub_ln878_fu_1009_p2, "sub_ln878_fu_1009_p2");
    sc_trace(mVcdFile, shl_ln9_fu_438_p3, "shl_ln9_fu_438_p3");
    sc_trace(mVcdFile, zext_ln477_fu_446_p1, "zext_ln477_fu_446_p1");
    sc_trace(mVcdFile, or_ln48_fu_493_p2, "or_ln48_fu_493_p2");
    sc_trace(mVcdFile, or_ln48_1_fu_563_p2, "or_ln48_1_fu_563_p2");
    sc_trace(mVcdFile, or_ln48_2_fu_573_p2, "or_ln48_2_fu_573_p2");
    sc_trace(mVcdFile, or_ln48_3_fu_583_p2, "or_ln48_3_fu_583_p2");
    sc_trace(mVcdFile, or_ln48_4_fu_593_p2, "or_ln48_4_fu_593_p2");
    sc_trace(mVcdFile, or_ln48_5_fu_603_p2, "or_ln48_5_fu_603_p2");
    sc_trace(mVcdFile, or_ln48_6_fu_613_p2, "or_ln48_6_fu_613_p2");
    sc_trace(mVcdFile, shl_ln_fu_643_p3, "shl_ln_fu_643_p3");
    sc_trace(mVcdFile, zext_ln855_fu_651_p1, "zext_ln855_fu_651_p1");
    sc_trace(mVcdFile, zext_ln854_fu_623_p1, "zext_ln854_fu_623_p1");
    sc_trace(mVcdFile, add_ln856_fu_666_p2, "add_ln856_fu_666_p2");
    sc_trace(mVcdFile, add_ln857_fu_676_p2, "add_ln857_fu_676_p2");
    sc_trace(mVcdFile, tmp_s_fu_686_p4, "tmp_s_fu_686_p4");
    sc_trace(mVcdFile, trunc_ln858_fu_699_p1, "trunc_ln858_fu_699_p1");
    sc_trace(mVcdFile, tmp_i_fu_703_p4, "tmp_i_fu_703_p4");
    sc_trace(mVcdFile, add_ln861_fu_717_p2, "add_ln861_fu_717_p2");
    sc_trace(mVcdFile, add_ln862_fu_727_p2, "add_ln862_fu_727_p2");
    sc_trace(mVcdFile, zext_ln860_fu_713_p1, "zext_ln860_fu_713_p1");
    sc_trace(mVcdFile, lshr_ln_fu_751_p4, "lshr_ln_fu_751_p4");
    sc_trace(mVcdFile, or_ln860_fu_765_p2, "or_ln860_fu_765_p2");
    sc_trace(mVcdFile, tmp_517_fu_771_p3, "tmp_517_fu_771_p3");
    sc_trace(mVcdFile, zext_ln860_1_fu_761_p1, "zext_ln860_1_fu_761_p1");
    sc_trace(mVcdFile, tmp_12_fu_795_p3, "tmp_12_fu_795_p3");
    sc_trace(mVcdFile, shl_ln6_fu_783_p3, "shl_ln6_fu_783_p3");
    sc_trace(mVcdFile, trunc_ln863_fu_791_p1, "trunc_ln863_fu_791_p1");
    sc_trace(mVcdFile, or_ln863_fu_803_p2, "or_ln863_fu_803_p2");
    sc_trace(mVcdFile, or_ln863_i_fu_809_p3, "or_ln863_i_fu_809_p3");
    sc_trace(mVcdFile, add_ln866_fu_821_p2, "add_ln866_fu_821_p2");
    sc_trace(mVcdFile, add_ln867_fu_831_p2, "add_ln867_fu_831_p2");
    sc_trace(mVcdFile, zext_ln863_fu_817_p1, "zext_ln863_fu_817_p1");
    sc_trace(mVcdFile, lshr_ln1_fu_848_p4, "lshr_ln1_fu_848_p4");
    sc_trace(mVcdFile, or_ln865_fu_862_p2, "or_ln865_fu_862_p2");
    sc_trace(mVcdFile, tmp_518_fu_867_p3, "tmp_518_fu_867_p3");
    sc_trace(mVcdFile, zext_ln865_fu_858_p1, "zext_ln865_fu_858_p1");
    sc_trace(mVcdFile, tmp_14_fu_891_p3, "tmp_14_fu_891_p3");
    sc_trace(mVcdFile, shl_ln7_fu_879_p3, "shl_ln7_fu_879_p3");
    sc_trace(mVcdFile, trunc_ln868_fu_887_p1, "trunc_ln868_fu_887_p1");
    sc_trace(mVcdFile, or_ln868_fu_899_p2, "or_ln868_fu_899_p2");
    sc_trace(mVcdFile, or_ln868_i_fu_905_p3, "or_ln868_i_fu_905_p3");
    sc_trace(mVcdFile, add_ln871_fu_917_p2, "add_ln871_fu_917_p2");
    sc_trace(mVcdFile, add_ln872_fu_927_p2, "add_ln872_fu_927_p2");
    sc_trace(mVcdFile, zext_ln868_fu_913_p1, "zext_ln868_fu_913_p1");
    sc_trace(mVcdFile, lshr_ln2_fu_944_p4, "lshr_ln2_fu_944_p4");
    sc_trace(mVcdFile, or_ln870_fu_958_p2, "or_ln870_fu_958_p2");
    sc_trace(mVcdFile, tmp_519_fu_963_p3, "tmp_519_fu_963_p3");
    sc_trace(mVcdFile, zext_ln870_fu_954_p1, "zext_ln870_fu_954_p1");
    sc_trace(mVcdFile, tmp_15_fu_983_p3, "tmp_15_fu_983_p3");
    sc_trace(mVcdFile, shl_ln8_fu_975_p3, "shl_ln8_fu_975_p3");
    sc_trace(mVcdFile, or_ln872_fu_991_p2, "or_ln872_fu_991_p2");
    sc_trace(mVcdFile, or_ln872_i_fu_997_p3, "or_ln872_i_fu_997_p3");
    sc_trace(mVcdFile, zext_ln872_1_fu_1005_p1, "zext_ln872_1_fu_1005_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

pqcrystals_dilithium_12::~pqcrystals_dilithium_12() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete buf_U;
    delete state_s_U;
    delete grp_KeccakF1600_StatePer_1_fu_399;
    delete grp_pqcrystals_dilithium_22_fu_406;
}

void pqcrystals_dilithium_12::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_KeccakF1600_StatePer_1_fu_399_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln474_fu_420_p2.read()))) {
            grp_KeccakF1600_StatePer_1_fu_399_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_KeccakF1600_StatePer_1_fu_399_ap_ready.read())) {
            grp_KeccakF1600_StatePer_1_fu_399_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pqcrystals_dilithium_22_fu_406_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_pqcrystals_dilithium_22_fu_406_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pqcrystals_dilithium_22_fu_406_ap_ready.read())) {
            grp_pqcrystals_dilithium_22_fu_406_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_0_i_i_reg_377 = i_23_reg_1035.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(grp_KeccakF1600_StatePer_1_fu_399_ap_done.read(), ap_const_logic_1))) {
        i_0_i_i_reg_377 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln474_fu_420_p2.read()))) {
        i_0_i_reg_388 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i_0_i_reg_388 = i_reg_1100.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln476_fu_426_p2.read(), ap_const_lv1_1))) {
        p_01_i_i_reg_353 = add_ln479_fu_467_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_pqcrystals_dilithium_22_fu_406_ap_done.read(), ap_const_logic_1))) {
        p_01_i_i_reg_353 = ap_const_lv3_5;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln476_fu_426_p2.read(), ap_const_lv1_1))) {
        p_0_rec_i_i_reg_365 = add_ln478_fu_461_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(grp_pqcrystals_dilithium_22_fu_406_ap_done.read(), ap_const_logic_1))) {
        p_0_rec_i_i_reg_365 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln476_fu_426_p2.read(), ap_const_lv1_0))) {
        add_ln477_reg_1040 = add_ln477_fu_450_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln854_fu_627_p2.read()))) {
        add_ln855_reg_1111 = add_ln855_fu_655_p2.read();
        trunc_ln855_reg_1105 = trunc_ln855_fu_639_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_23_reg_1035 = i_23_fu_432_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_reg_1100 = i_fu_633_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        reg_416 = buf_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        shl_ln855_1_reg_1148 = shl_ln855_1_fu_744_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        trunc_ln48_2_reg_1067 = state_s_q0.read().range(23, 16);
        trunc_ln48_3_reg_1072 = state_s_q0.read().range(31, 24);
        trunc_ln48_4_reg_1077 = state_s_q0.read().range(39, 32);
        trunc_ln48_5_reg_1082 = state_s_q0.read().range(47, 40);
        trunc_ln48_6_reg_1087 = state_s_q0.read().range(55, 48);
        trunc_ln48_7_reg_1092 = state_s_q0.read().range(63, 56);
    }
}

void pqcrystals_dilithium_12::thread_a_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        a_coeffs_address0 =  (sc_lv<10>) (zext_ln870_1_fu_970_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        a_coeffs_address0 =  (sc_lv<10>) (zext_ln865_1_fu_874_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        a_coeffs_address0 =  (sc_lv<10>) (zext_ln860_2_fu_778_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        a_coeffs_address0 =  (sc_lv<10>) (zext_ln855_2_fu_694_p1.read());
    } else {
        a_coeffs_address0 = "XXXXXXXXXX";
    }
}

void pqcrystals_dilithium_12::thread_a_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        a_coeffs_ce0 = ap_const_logic_1;
    } else {
        a_coeffs_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_a_coeffs_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        a_coeffs_d0 = sub_ln878_fu_1009_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        a_coeffs_d0 = sub_ln877_fu_937_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        a_coeffs_d0 = sub_ln876_fu_841_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        a_coeffs_d0 = sub_ln875_fu_737_p2.read();
    } else {
        a_coeffs_d0 =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
    }
}

void pqcrystals_dilithium_12::thread_a_coeffs_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        a_coeffs_we0 = ap_const_logic_1;
    } else {
        a_coeffs_we0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_add_ln477_fu_450_p2() {
    add_ln477_fu_450_p2 = (!p_0_rec_i_i_reg_365.read().is_01() || !zext_ln477_fu_446_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(p_0_rec_i_i_reg_365.read()) + sc_biguint<10>(zext_ln477_fu_446_p1.read()));
}

void pqcrystals_dilithium_12::thread_add_ln478_fu_461_p2() {
    add_ln478_fu_461_p2 = (!p_0_rec_i_i_reg_365.read().is_01() || !ap_const_lv10_88.is_01())? sc_lv<10>(): (sc_biguint<10>(p_0_rec_i_i_reg_365.read()) + sc_biguint<10>(ap_const_lv10_88));
}

void pqcrystals_dilithium_12::thread_add_ln479_fu_467_p2() {
    add_ln479_fu_467_p2 = (!p_01_i_i_reg_353.read().is_01() || !ap_const_lv3_7.is_01())? sc_lv<3>(): (sc_biguint<3>(p_01_i_i_reg_353.read()) + sc_bigint<3>(ap_const_lv3_7));
}

void pqcrystals_dilithium_12::thread_add_ln855_fu_655_p2() {
    add_ln855_fu_655_p2 = (!zext_ln855_fu_651_p1.read().is_01() || !zext_ln854_fu_623_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln855_fu_651_p1.read()) + sc_biguint<10>(zext_ln854_fu_623_p1.read()));
}

void pqcrystals_dilithium_12::thread_add_ln856_fu_666_p2() {
    add_ln856_fu_666_p2 = (!ap_const_lv10_1.is_01() || !add_ln855_reg_1111.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_1) + sc_biguint<10>(add_ln855_reg_1111.read()));
}

void pqcrystals_dilithium_12::thread_add_ln857_fu_676_p2() {
    add_ln857_fu_676_p2 = (!ap_const_lv10_2.is_01() || !add_ln855_reg_1111.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_2) + sc_biguint<10>(add_ln855_reg_1111.read()));
}

void pqcrystals_dilithium_12::thread_add_ln861_fu_717_p2() {
    add_ln861_fu_717_p2 = (!ap_const_lv10_3.is_01() || !add_ln855_reg_1111.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_3) + sc_biguint<10>(add_ln855_reg_1111.read()));
}

void pqcrystals_dilithium_12::thread_add_ln862_fu_727_p2() {
    add_ln862_fu_727_p2 = (!ap_const_lv10_4.is_01() || !add_ln855_reg_1111.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_4) + sc_biguint<10>(add_ln855_reg_1111.read()));
}

void pqcrystals_dilithium_12::thread_add_ln866_fu_821_p2() {
    add_ln866_fu_821_p2 = (!ap_const_lv10_5.is_01() || !add_ln855_reg_1111.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_5) + sc_biguint<10>(add_ln855_reg_1111.read()));
}

void pqcrystals_dilithium_12::thread_add_ln867_fu_831_p2() {
    add_ln867_fu_831_p2 = (!ap_const_lv10_6.is_01() || !add_ln855_reg_1111.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_6) + sc_biguint<10>(add_ln855_reg_1111.read()));
}

void pqcrystals_dilithium_12::thread_add_ln871_fu_917_p2() {
    add_ln871_fu_917_p2 = (!ap_const_lv10_7.is_01() || !add_ln855_reg_1111.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_7) + sc_biguint<10>(add_ln855_reg_1111.read()));
}

void pqcrystals_dilithium_12::thread_add_ln872_fu_927_p2() {
    add_ln872_fu_927_p2 = (!ap_const_lv10_8.is_01() || !add_ln855_reg_1111.read().is_01())? sc_lv<10>(): (sc_biguint<10>(ap_const_lv10_8) + sc_biguint<10>(add_ln855_reg_1111.read()));
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void pqcrystals_dilithium_12::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void pqcrystals_dilithium_12::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln854_fu_627_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln854_fu_627_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_buf_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        buf_address0 =  (sc_lv<10>) (zext_ln872_fu_932_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        buf_address0 =  (sc_lv<10>) (zext_ln867_fu_836_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        buf_address0 =  (sc_lv<10>) (zext_ln862_fu_732_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        buf_address0 =  (sc_lv<10>) (zext_ln857_fu_681_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        buf_address0 =  (sc_lv<10>) (zext_ln855_1_fu_661_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        buf_address0 =  (sc_lv<10>) (zext_ln48_5_fu_608_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        buf_address0 =  (sc_lv<10>) (zext_ln48_3_fu_588_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_address0 =  (sc_lv<10>) (zext_ln48_1_fu_568_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        buf_address0 =  (sc_lv<10>) (zext_ln477_2_fu_473_p1.read());
    } else {
        buf_address0 = "XXXXXXXXXX";
    }
}

void pqcrystals_dilithium_12::thread_buf_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        buf_address1 =  (sc_lv<10>) (zext_ln871_fu_922_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        buf_address1 =  (sc_lv<10>) (zext_ln866_fu_826_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        buf_address1 =  (sc_lv<10>) (zext_ln861_fu_722_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        buf_address1 =  (sc_lv<10>) (zext_ln856_fu_671_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        buf_address1 =  (sc_lv<10>) (zext_ln48_6_fu_618_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        buf_address1 =  (sc_lv<10>) (zext_ln48_4_fu_598_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_address1 =  (sc_lv<10>) (zext_ln48_2_fu_578_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        buf_address1 =  (sc_lv<10>) (zext_ln48_fu_498_p1.read());
    } else {
        buf_address1 = "XXXXXXXXXX";
    }
}

void pqcrystals_dilithium_12::thread_buf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        buf_ce0 = ap_const_logic_1;
    } else {
        buf_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_buf_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        buf_ce1 = ap_const_logic_1;
    } else {
        buf_ce1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_buf_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        buf_d0 = trunc_ln48_6_reg_1087.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        buf_d0 = trunc_ln48_4_reg_1077.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_d0 = trunc_ln48_2_reg_1067.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        buf_d0 = trunc_ln48_fu_477_p1.read();
    } else {
        buf_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void pqcrystals_dilithium_12::thread_buf_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        buf_d1 = trunc_ln48_7_reg_1092.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        buf_d1 = trunc_ln48_5_reg_1082.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_d1 = trunc_ln48_3_reg_1072.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        buf_d1 = state_s_q0.read().range(15, 8);
    } else {
        buf_d1 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void pqcrystals_dilithium_12::thread_buf_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        buf_we0 = ap_const_logic_1;
    } else {
        buf_we0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_buf_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        buf_we1 = ap_const_logic_1;
    } else {
        buf_we1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_grp_KeccakF1600_StatePer_1_fu_399_ap_start() {
    grp_KeccakF1600_StatePer_1_fu_399_ap_start = grp_KeccakF1600_StatePer_1_fu_399_ap_start_reg.read();
}

void pqcrystals_dilithium_12::thread_grp_pqcrystals_dilithium_22_fu_406_ap_start() {
    grp_pqcrystals_dilithium_22_fu_406_ap_start = grp_pqcrystals_dilithium_22_fu_406_ap_start_reg.read();
}

void pqcrystals_dilithium_12::thread_i_23_fu_432_p2() {
    i_23_fu_432_p2 = (!i_0_i_i_reg_377.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_i_i_reg_377.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void pqcrystals_dilithium_12::thread_i_fu_633_p2() {
    i_fu_633_p2 = (!i_0_i_reg_388.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_0_i_reg_388.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void pqcrystals_dilithium_12::thread_icmp_ln474_fu_420_p2() {
    icmp_ln474_fu_420_p2 = (!p_01_i_i_reg_353.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(p_01_i_i_reg_353.read() == ap_const_lv3_0);
}

void pqcrystals_dilithium_12::thread_icmp_ln476_fu_426_p2() {
    icmp_ln476_fu_426_p2 = (!i_0_i_i_reg_377.read().is_01() || !ap_const_lv5_11.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_i_reg_377.read() == ap_const_lv5_11);
}

void pqcrystals_dilithium_12::thread_icmp_ln854_fu_627_p2() {
    icmp_ln854_fu_627_p2 = (!i_0_i_reg_388.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_388.read() == ap_const_lv7_40);
}

void pqcrystals_dilithium_12::thread_lshr_ln1_fu_848_p4() {
    lshr_ln1_fu_848_p4 = reg_416.read().range(7, 4);
}

void pqcrystals_dilithium_12::thread_lshr_ln2_fu_944_p4() {
    lshr_ln2_fu_944_p4 = reg_416.read().range(7, 6);
}

void pqcrystals_dilithium_12::thread_lshr_ln_fu_751_p4() {
    lshr_ln_fu_751_p4 = reg_416.read().range(7, 2);
}

void pqcrystals_dilithium_12::thread_or_ln48_1_fu_563_p2() {
    or_ln48_1_fu_563_p2 = (add_ln477_reg_1040.read() | ap_const_lv10_2);
}

void pqcrystals_dilithium_12::thread_or_ln48_2_fu_573_p2() {
    or_ln48_2_fu_573_p2 = (add_ln477_reg_1040.read() | ap_const_lv10_3);
}

void pqcrystals_dilithium_12::thread_or_ln48_3_fu_583_p2() {
    or_ln48_3_fu_583_p2 = (add_ln477_reg_1040.read() | ap_const_lv10_4);
}

void pqcrystals_dilithium_12::thread_or_ln48_4_fu_593_p2() {
    or_ln48_4_fu_593_p2 = (add_ln477_reg_1040.read() | ap_const_lv10_5);
}

void pqcrystals_dilithium_12::thread_or_ln48_5_fu_603_p2() {
    or_ln48_5_fu_603_p2 = (add_ln477_reg_1040.read() | ap_const_lv10_6);
}

void pqcrystals_dilithium_12::thread_or_ln48_6_fu_613_p2() {
    or_ln48_6_fu_613_p2 = (add_ln477_reg_1040.read() | ap_const_lv10_7);
}

void pqcrystals_dilithium_12::thread_or_ln48_fu_493_p2() {
    or_ln48_fu_493_p2 = (add_ln477_reg_1040.read() | ap_const_lv10_1);
}

void pqcrystals_dilithium_12::thread_or_ln860_fu_765_p2() {
    or_ln860_fu_765_p2 = (shl_ln855_1_fu_744_p3.read() | ap_const_lv8_1);
}

void pqcrystals_dilithium_12::thread_or_ln863_fu_803_p2() {
    or_ln863_fu_803_p2 = (tmp_12_fu_795_p3.read() | shl_ln6_fu_783_p3.read());
}

void pqcrystals_dilithium_12::thread_or_ln863_i_fu_809_p3() {
    or_ln863_i_fu_809_p3 = esl_concat<4,14>(trunc_ln863_fu_791_p1.read(), or_ln863_fu_803_p2.read());
}

void pqcrystals_dilithium_12::thread_or_ln865_fu_862_p2() {
    or_ln865_fu_862_p2 = (shl_ln855_1_reg_1148.read() | ap_const_lv8_2);
}

void pqcrystals_dilithium_12::thread_or_ln868_fu_899_p2() {
    or_ln868_fu_899_p2 = (tmp_14_fu_891_p3.read() | shl_ln7_fu_879_p3.read());
}

void pqcrystals_dilithium_12::thread_or_ln868_i_fu_905_p3() {
    or_ln868_i_fu_905_p3 = esl_concat<6,12>(trunc_ln868_fu_887_p1.read(), or_ln868_fu_899_p2.read());
}

void pqcrystals_dilithium_12::thread_or_ln870_fu_958_p2() {
    or_ln870_fu_958_p2 = (shl_ln855_1_reg_1148.read() | ap_const_lv8_3);
}

void pqcrystals_dilithium_12::thread_or_ln872_fu_991_p2() {
    or_ln872_fu_991_p2 = (tmp_15_fu_983_p3.read() | shl_ln8_fu_975_p3.read());
}

void pqcrystals_dilithium_12::thread_or_ln872_i_fu_997_p3() {
    or_ln872_i_fu_997_p3 = esl_concat<8,10>(buf_q0.read(), or_ln872_fu_991_p2.read());
}

void pqcrystals_dilithium_12::thread_seed_address0() {
    seed_address0 = grp_pqcrystals_dilithium_22_fu_406_seed_address0.read();
}

void pqcrystals_dilithium_12::thread_seed_address1() {
    seed_address1 = grp_pqcrystals_dilithium_22_fu_406_seed_address1.read();
}

void pqcrystals_dilithium_12::thread_seed_ce0() {
    seed_ce0 = grp_pqcrystals_dilithium_22_fu_406_seed_ce0.read();
}

void pqcrystals_dilithium_12::thread_seed_ce1() {
    seed_ce1 = grp_pqcrystals_dilithium_22_fu_406_seed_ce1.read();
}

void pqcrystals_dilithium_12::thread_shl_ln6_fu_783_p3() {
    shl_ln6_fu_783_p3 = esl_concat<8,6>(buf_q1.read(), ap_const_lv6_0);
}

void pqcrystals_dilithium_12::thread_shl_ln7_fu_879_p3() {
    shl_ln7_fu_879_p3 = esl_concat<8,4>(buf_q1.read(), ap_const_lv4_0);
}

void pqcrystals_dilithium_12::thread_shl_ln855_1_fu_744_p3() {
    shl_ln855_1_fu_744_p3 = esl_concat<6,2>(trunc_ln855_reg_1105.read(), ap_const_lv2_0);
}

void pqcrystals_dilithium_12::thread_shl_ln8_fu_975_p3() {
    shl_ln8_fu_975_p3 = esl_concat<8,2>(buf_q1.read(), ap_const_lv2_0);
}

void pqcrystals_dilithium_12::thread_shl_ln9_fu_438_p3() {
    shl_ln9_fu_438_p3 = esl_concat<5,3>(i_0_i_i_reg_377.read(), ap_const_lv3_0);
}

void pqcrystals_dilithium_12::thread_shl_ln_fu_643_p3() {
    shl_ln_fu_643_p3 = esl_concat<6,3>(trunc_ln855_fu_639_p1.read(), ap_const_lv3_0);
}

void pqcrystals_dilithium_12::thread_state_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_s_address0 =  (sc_lv<5>) (zext_ln477_1_fu_456_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_address0 = grp_pqcrystals_dilithium_22_fu_406_state_s_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_s_address0 = grp_KeccakF1600_StatePer_1_fu_399_state_address0.read();
    } else {
        state_s_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void pqcrystals_dilithium_12::thread_state_s_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_address1 = grp_pqcrystals_dilithium_22_fu_406_state_s_address1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_s_address1 = grp_KeccakF1600_StatePer_1_fu_399_state_address1.read();
    } else {
        state_s_address1 =  (sc_lv<5>) ("XXXXX");
    }
}

void pqcrystals_dilithium_12::thread_state_s_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        state_s_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_ce0 = grp_pqcrystals_dilithium_22_fu_406_state_s_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_s_ce0 = grp_KeccakF1600_StatePer_1_fu_399_state_ce0.read();
    } else {
        state_s_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_state_s_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_ce1 = grp_pqcrystals_dilithium_22_fu_406_state_s_ce1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_s_ce1 = grp_KeccakF1600_StatePer_1_fu_399_state_ce1.read();
    } else {
        state_s_ce1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_state_s_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_d0 = grp_pqcrystals_dilithium_22_fu_406_state_s_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_s_d0 = grp_KeccakF1600_StatePer_1_fu_399_state_d0.read();
    } else {
        state_s_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void pqcrystals_dilithium_12::thread_state_s_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_d1 = grp_pqcrystals_dilithium_22_fu_406_state_s_d1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_s_d1 = grp_KeccakF1600_StatePer_1_fu_399_state_d1.read();
    } else {
        state_s_d1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void pqcrystals_dilithium_12::thread_state_s_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_we0 = grp_pqcrystals_dilithium_22_fu_406_state_s_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_s_we0 = grp_KeccakF1600_StatePer_1_fu_399_state_we0.read();
    } else {
        state_s_we0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_state_s_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_we1 = grp_pqcrystals_dilithium_22_fu_406_state_s_we1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_s_we1 = grp_KeccakF1600_StatePer_1_fu_399_state_we1.read();
    } else {
        state_s_we1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_12::thread_sub_ln875_fu_737_p2() {
    sub_ln875_fu_737_p2 = (!ap_const_lv19_20000.is_01() || !zext_ln860_fu_713_p1.read().is_01())? sc_lv<19>(): (sc_biguint<19>(ap_const_lv19_20000) - sc_biguint<19>(zext_ln860_fu_713_p1.read()));
}

void pqcrystals_dilithium_12::thread_sub_ln876_fu_841_p2() {
    sub_ln876_fu_841_p2 = (!ap_const_lv19_20000.is_01() || !zext_ln863_fu_817_p1.read().is_01())? sc_lv<19>(): (sc_biguint<19>(ap_const_lv19_20000) - sc_biguint<19>(zext_ln863_fu_817_p1.read()));
}

void pqcrystals_dilithium_12::thread_sub_ln877_fu_937_p2() {
    sub_ln877_fu_937_p2 = (!ap_const_lv19_20000.is_01() || !zext_ln868_fu_913_p1.read().is_01())? sc_lv<19>(): (sc_biguint<19>(ap_const_lv19_20000) - sc_biguint<19>(zext_ln868_fu_913_p1.read()));
}

void pqcrystals_dilithium_12::thread_sub_ln878_fu_1009_p2() {
    sub_ln878_fu_1009_p2 = (!ap_const_lv19_20000.is_01() || !zext_ln872_1_fu_1005_p1.read().is_01())? sc_lv<19>(): (sc_biguint<19>(ap_const_lv19_20000) - sc_biguint<19>(zext_ln872_1_fu_1005_p1.read()));
}

void pqcrystals_dilithium_12::thread_tmp_12_fu_795_p3() {
    tmp_12_fu_795_p3 = esl_concat<6,8>(ap_const_lv6_0, zext_ln860_1_fu_761_p1.read());
}

void pqcrystals_dilithium_12::thread_tmp_14_fu_891_p3() {
    tmp_14_fu_891_p3 = esl_concat<4,8>(ap_const_lv4_0, zext_ln865_fu_858_p1.read());
}

void pqcrystals_dilithium_12::thread_tmp_15_fu_983_p3() {
    tmp_15_fu_983_p3 = esl_concat<2,8>(ap_const_lv2_0, zext_ln870_fu_954_p1.read());
}

void pqcrystals_dilithium_12::thread_tmp_517_fu_771_p3() {
    tmp_517_fu_771_p3 = esl_concat<3,8>(a_coeffs_offset.read(), or_ln860_fu_765_p2.read());
}

void pqcrystals_dilithium_12::thread_tmp_518_fu_867_p3() {
    tmp_518_fu_867_p3 = esl_concat<3,8>(a_coeffs_offset.read(), or_ln865_fu_862_p2.read());
}

void pqcrystals_dilithium_12::thread_tmp_519_fu_963_p3() {
    tmp_519_fu_963_p3 = esl_concat<3,8>(a_coeffs_offset.read(), or_ln870_fu_958_p2.read());
}

void pqcrystals_dilithium_12::thread_tmp_i_fu_703_p4() {
    tmp_i_fu_703_p4 = esl_concat<10,8>(esl_concat<2,8>(trunc_ln858_fu_699_p1.read(), buf_q1.read()), reg_416.read());
}

void pqcrystals_dilithium_12::thread_tmp_s_fu_686_p4() {
    tmp_s_fu_686_p4 = esl_concat<9,2>(esl_concat<3,6>(a_coeffs_offset.read(), trunc_ln855_reg_1105.read()), ap_const_lv2_0);
}

void pqcrystals_dilithium_12::thread_trunc_ln48_fu_477_p1() {
    trunc_ln48_fu_477_p1 = state_s_q0.read().range(8-1, 0);
}

void pqcrystals_dilithium_12::thread_trunc_ln855_fu_639_p1() {
    trunc_ln855_fu_639_p1 = i_0_i_reg_388.read().range(6-1, 0);
}

void pqcrystals_dilithium_12::thread_trunc_ln858_fu_699_p1() {
    trunc_ln858_fu_699_p1 = buf_q0.read().range(2-1, 0);
}

void pqcrystals_dilithium_12::thread_trunc_ln863_fu_791_p1() {
    trunc_ln863_fu_791_p1 = buf_q0.read().range(4-1, 0);
}

void pqcrystals_dilithium_12::thread_trunc_ln868_fu_887_p1() {
    trunc_ln868_fu_887_p1 = buf_q0.read().range(6-1, 0);
}

void pqcrystals_dilithium_12::thread_zext_ln477_1_fu_456_p1() {
    zext_ln477_1_fu_456_p1 = esl_zext<64,5>(i_0_i_i_reg_377.read());
}

void pqcrystals_dilithium_12::thread_zext_ln477_2_fu_473_p1() {
    zext_ln477_2_fu_473_p1 = esl_zext<64,10>(add_ln477_reg_1040.read());
}

void pqcrystals_dilithium_12::thread_zext_ln477_fu_446_p1() {
    zext_ln477_fu_446_p1 = esl_zext<10,8>(shl_ln9_fu_438_p3.read());
}

void pqcrystals_dilithium_12::thread_zext_ln48_1_fu_568_p1() {
    zext_ln48_1_fu_568_p1 = esl_zext<64,10>(or_ln48_1_fu_563_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln48_2_fu_578_p1() {
    zext_ln48_2_fu_578_p1 = esl_zext<64,10>(or_ln48_2_fu_573_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln48_3_fu_588_p1() {
    zext_ln48_3_fu_588_p1 = esl_zext<64,10>(or_ln48_3_fu_583_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln48_4_fu_598_p1() {
    zext_ln48_4_fu_598_p1 = esl_zext<64,10>(or_ln48_4_fu_593_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln48_5_fu_608_p1() {
    zext_ln48_5_fu_608_p1 = esl_zext<64,10>(or_ln48_5_fu_603_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln48_6_fu_618_p1() {
    zext_ln48_6_fu_618_p1 = esl_zext<64,10>(or_ln48_6_fu_613_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln48_fu_498_p1() {
    zext_ln48_fu_498_p1 = esl_zext<64,10>(or_ln48_fu_493_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln854_fu_623_p1() {
    zext_ln854_fu_623_p1 = esl_zext<10,7>(i_0_i_reg_388.read());
}

void pqcrystals_dilithium_12::thread_zext_ln855_1_fu_661_p1() {
    zext_ln855_1_fu_661_p1 = esl_zext<64,10>(add_ln855_fu_655_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln855_2_fu_694_p1() {
    zext_ln855_2_fu_694_p1 = esl_zext<64,11>(tmp_s_fu_686_p4.read());
}

void pqcrystals_dilithium_12::thread_zext_ln855_fu_651_p1() {
    zext_ln855_fu_651_p1 = esl_zext<10,9>(shl_ln_fu_643_p3.read());
}

void pqcrystals_dilithium_12::thread_zext_ln856_fu_671_p1() {
    zext_ln856_fu_671_p1 = esl_zext<64,10>(add_ln856_fu_666_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln857_fu_681_p1() {
    zext_ln857_fu_681_p1 = esl_zext<64,10>(add_ln857_fu_676_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln860_1_fu_761_p1() {
    zext_ln860_1_fu_761_p1 = esl_zext<8,6>(lshr_ln_fu_751_p4.read());
}

void pqcrystals_dilithium_12::thread_zext_ln860_2_fu_778_p1() {
    zext_ln860_2_fu_778_p1 = esl_zext<64,11>(tmp_517_fu_771_p3.read());
}

void pqcrystals_dilithium_12::thread_zext_ln860_fu_713_p1() {
    zext_ln860_fu_713_p1 = esl_zext<19,18>(tmp_i_fu_703_p4.read());
}

void pqcrystals_dilithium_12::thread_zext_ln861_fu_722_p1() {
    zext_ln861_fu_722_p1 = esl_zext<64,10>(add_ln861_fu_717_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln862_fu_732_p1() {
    zext_ln862_fu_732_p1 = esl_zext<64,10>(add_ln862_fu_727_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln863_fu_817_p1() {
    zext_ln863_fu_817_p1 = esl_zext<19,18>(or_ln863_i_fu_809_p3.read());
}

void pqcrystals_dilithium_12::thread_zext_ln865_1_fu_874_p1() {
    zext_ln865_1_fu_874_p1 = esl_zext<64,11>(tmp_518_fu_867_p3.read());
}

void pqcrystals_dilithium_12::thread_zext_ln865_fu_858_p1() {
    zext_ln865_fu_858_p1 = esl_zext<8,4>(lshr_ln1_fu_848_p4.read());
}

void pqcrystals_dilithium_12::thread_zext_ln866_fu_826_p1() {
    zext_ln866_fu_826_p1 = esl_zext<64,10>(add_ln866_fu_821_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln867_fu_836_p1() {
    zext_ln867_fu_836_p1 = esl_zext<64,10>(add_ln867_fu_831_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln868_fu_913_p1() {
    zext_ln868_fu_913_p1 = esl_zext<19,18>(or_ln868_i_fu_905_p3.read());
}

void pqcrystals_dilithium_12::thread_zext_ln870_1_fu_970_p1() {
    zext_ln870_1_fu_970_p1 = esl_zext<64,11>(tmp_519_fu_963_p3.read());
}

void pqcrystals_dilithium_12::thread_zext_ln870_fu_954_p1() {
    zext_ln870_fu_954_p1 = esl_zext<8,2>(lshr_ln2_fu_944_p4.read());
}

void pqcrystals_dilithium_12::thread_zext_ln871_fu_922_p1() {
    zext_ln871_fu_922_p1 = esl_zext<64,10>(add_ln871_fu_917_p2.read());
}

void pqcrystals_dilithium_12::thread_zext_ln872_1_fu_1005_p1() {
    zext_ln872_1_fu_1005_p1 = esl_zext<19,18>(or_ln872_i_fu_997_p3.read());
}

void pqcrystals_dilithium_12::thread_zext_ln872_fu_932_p1() {
    zext_ln872_fu_932_p1 = esl_zext<64,10>(add_ln872_fu_927_p2.read());
}

void pqcrystals_dilithium_12::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_pqcrystals_dilithium_22_fu_406_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln474_fu_420_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_KeccakF1600_StatePer_1_fu_399_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln476_fu_426_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln854_fu_627_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
            break;
    }
}

}

