// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pqcrystals_dilithium2_ref.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pqcrystals_dilithium2_ref::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pqcrystals_dilithium2_ref::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> pqcrystals_dilithium2_ref::ap_ST_fsm_state1 = "1";
const sc_lv<4> pqcrystals_dilithium2_ref::ap_ST_fsm_state2 = "10";
const sc_lv<4> pqcrystals_dilithium2_ref::ap_ST_fsm_state3 = "100";
const sc_lv<4> pqcrystals_dilithium2_ref::ap_ST_fsm_state4 = "1000";
const sc_lv<32> pqcrystals_dilithium2_ref::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pqcrystals_dilithium2_ref::ap_const_lv32_1 = "1";
const sc_lv<1> pqcrystals_dilithium2_ref::ap_const_lv1_0 = "0";
const sc_lv<64> pqcrystals_dilithium2_ref::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> pqcrystals_dilithium2_ref::ap_const_lv32_2 = "10";
const sc_lv<1> pqcrystals_dilithium2_ref::ap_const_lv1_1 = "1";
const sc_lv<32> pqcrystals_dilithium2_ref::ap_const_lv32_3 = "11";
const sc_lv<13> pqcrystals_dilithium2_ref::ap_const_lv13_1FFF = "1111111111111";
const sc_lv<14> pqcrystals_dilithium2_ref::ap_const_lv14_973 = "100101110011";
const sc_lv<64> pqcrystals_dilithium2_ref::ap_const_lv64_1 = "1";
const sc_lv<64> pqcrystals_dilithium2_ref::ap_const_lv64_974 = "100101110100";
const bool pqcrystals_dilithium2_ref::ap_const_boolean_1 = true;

pqcrystals_dilithium2_ref::pqcrystals_dilithium2_ref(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_pqcrystals_dilithium_1_1_fu_107 = new pqcrystals_dilithium_1_1("grp_pqcrystals_dilithium_1_1_fu_107");
    grp_pqcrystals_dilithium_1_1_fu_107->ap_clk(ap_clk);
    grp_pqcrystals_dilithium_1_1_fu_107->ap_rst(ap_rst);
    grp_pqcrystals_dilithium_1_1_fu_107->ap_start(grp_pqcrystals_dilithium_1_1_fu_107_ap_start);
    grp_pqcrystals_dilithium_1_1_fu_107->ap_done(grp_pqcrystals_dilithium_1_1_fu_107_ap_done);
    grp_pqcrystals_dilithium_1_1_fu_107->ap_idle(grp_pqcrystals_dilithium_1_1_fu_107_ap_idle);
    grp_pqcrystals_dilithium_1_1_fu_107->ap_ready(grp_pqcrystals_dilithium_1_1_fu_107_ap_ready);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_address0(grp_pqcrystals_dilithium_1_1_fu_107_sig_address0);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_ce0(grp_pqcrystals_dilithium_1_1_fu_107_sig_ce0);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_we0(grp_pqcrystals_dilithium_1_1_fu_107_sig_we0);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_d0(grp_pqcrystals_dilithium_1_1_fu_107_sig_d0);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_q0(sm_q0);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_address1(grp_pqcrystals_dilithium_1_1_fu_107_sig_address1);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_ce1(grp_pqcrystals_dilithium_1_1_fu_107_sig_ce1);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_we1(grp_pqcrystals_dilithium_1_1_fu_107_sig_we1);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_d1(grp_pqcrystals_dilithium_1_1_fu_107_sig_d1);
    grp_pqcrystals_dilithium_1_1_fu_107->sig_q1(sm_q1);
    grp_pqcrystals_dilithium_1_1_fu_107->mlen(mlen);
    grp_pqcrystals_dilithium_1_1_fu_107->sk_address0(grp_pqcrystals_dilithium_1_1_fu_107_sk_address0);
    grp_pqcrystals_dilithium_1_1_fu_107->sk_ce0(grp_pqcrystals_dilithium_1_1_fu_107_sk_ce0);
    grp_pqcrystals_dilithium_1_1_fu_107->sk_q0(sk_q0);
    grp_pqcrystals_dilithium_1_1_fu_107->sk_address1(grp_pqcrystals_dilithium_1_1_fu_107_sk_address1);
    grp_pqcrystals_dilithium_1_1_fu_107->sk_ce1(grp_pqcrystals_dilithium_1_1_fu_107_sk_ce1);
    grp_pqcrystals_dilithium_1_1_fu_107->sk_q1(sk_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln213_1_fu_134_p2);
    sensitive << ( trunc_ln213_1_fu_130_p1 );

    SC_METHOD(thread_add_ln213_fu_124_p2);
    sensitive << ( trunc_ln213_fu_120_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_ap_done );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_ap_done );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_ap_done );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_pqcrystals_dilithium_1_1_fu_107_ap_start);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_ap_start_reg );

    SC_METHOD(thread_i_fu_153_p2);
    sensitive << ( i_0_reg_96 );

    SC_METHOD(thread_icmp_ln212_fu_148_p2);
    sensitive << ( mlen );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_96 );

    SC_METHOD(thread_m_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln213_fu_164_p1 );

    SC_METHOD(thread_m_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sk_address0);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sk_address0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sk_address1);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sk_address1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sk_ce0);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sk_ce0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sk_ce1);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sk_ce1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sm_address0);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sig_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln213_1_fu_180_p1 );

    SC_METHOD(thread_sm_address1);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sig_address1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sm_ce0);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sig_ce0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sm_ce1);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sig_ce1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sm_d0);
    sensitive << ( m_q0 );
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sig_d0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sm_d1);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sig_d1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sm_we0);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sig_we0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sm_we1);
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_sig_we1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_smlen);
    sensitive << ( mlen );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln212_fu_148_p2 );

    SC_METHOD(thread_smlen_ap_vld);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln212_fu_148_p2 );

    SC_METHOD(thread_sub_ln213_1_fu_169_p2);
    sensitive << ( add_ln213_1_reg_196 );
    sensitive << ( trunc_ln212_fu_140_p1 );

    SC_METHOD(thread_sub_ln213_fu_159_p2);
    sensitive << ( add_ln213_reg_191 );
    sensitive << ( trunc_ln212_1_fu_144_p1 );

    SC_METHOD(thread_trunc_ln212_1_fu_144_p1);
    sensitive << ( i_0_reg_96 );

    SC_METHOD(thread_trunc_ln212_fu_140_p1);
    sensitive << ( i_0_reg_96 );

    SC_METHOD(thread_trunc_ln213_1_fu_130_p1);
    sensitive << ( mlen );

    SC_METHOD(thread_trunc_ln213_fu_120_p1);
    sensitive << ( mlen );

    SC_METHOD(thread_zext_ln213_1_fu_180_p1);
    sensitive << ( sub_ln213_1_reg_214 );

    SC_METHOD(thread_zext_ln213_fu_164_p1);
    sensitive << ( sub_ln213_fu_159_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln212_fu_148_p2 );
    sensitive << ( grp_pqcrystals_dilithium_1_1_fu_107_ap_done );
    sensitive << ( ap_CS_fsm_state4 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0001";
    grp_pqcrystals_dilithium_1_1_fu_107_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pqcrystals_dilithium2_ref_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, sm_address0, "(port)sm_address0");
    sc_trace(mVcdFile, sm_ce0, "(port)sm_ce0");
    sc_trace(mVcdFile, sm_we0, "(port)sm_we0");
    sc_trace(mVcdFile, sm_d0, "(port)sm_d0");
    sc_trace(mVcdFile, sm_q0, "(port)sm_q0");
    sc_trace(mVcdFile, sm_address1, "(port)sm_address1");
    sc_trace(mVcdFile, sm_ce1, "(port)sm_ce1");
    sc_trace(mVcdFile, sm_we1, "(port)sm_we1");
    sc_trace(mVcdFile, sm_d1, "(port)sm_d1");
    sc_trace(mVcdFile, sm_q1, "(port)sm_q1");
    sc_trace(mVcdFile, smlen, "(port)smlen");
    sc_trace(mVcdFile, smlen_ap_vld, "(port)smlen_ap_vld");
    sc_trace(mVcdFile, m_address0, "(port)m_address0");
    sc_trace(mVcdFile, m_ce0, "(port)m_ce0");
    sc_trace(mVcdFile, m_q0, "(port)m_q0");
    sc_trace(mVcdFile, mlen, "(port)mlen");
    sc_trace(mVcdFile, sk_address0, "(port)sk_address0");
    sc_trace(mVcdFile, sk_ce0, "(port)sk_ce0");
    sc_trace(mVcdFile, sk_q0, "(port)sk_q0");
    sc_trace(mVcdFile, sk_address1, "(port)sk_address1");
    sc_trace(mVcdFile, sk_ce1, "(port)sk_ce1");
    sc_trace(mVcdFile, sk_q1, "(port)sk_q1");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, add_ln213_fu_124_p2, "add_ln213_fu_124_p2");
    sc_trace(mVcdFile, add_ln213_reg_191, "add_ln213_reg_191");
    sc_trace(mVcdFile, add_ln213_1_fu_134_p2, "add_ln213_1_fu_134_p2");
    sc_trace(mVcdFile, add_ln213_1_reg_196, "add_ln213_1_reg_196");
    sc_trace(mVcdFile, i_fu_153_p2, "i_fu_153_p2");
    sc_trace(mVcdFile, i_reg_204, "i_reg_204");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln212_fu_148_p2, "icmp_ln212_fu_148_p2");
    sc_trace(mVcdFile, sub_ln213_1_fu_169_p2, "sub_ln213_1_fu_169_p2");
    sc_trace(mVcdFile, sub_ln213_1_reg_214, "sub_ln213_1_reg_214");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_ap_start, "grp_pqcrystals_dilithium_1_1_fu_107_ap_start");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_ap_done, "grp_pqcrystals_dilithium_1_1_fu_107_ap_done");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_ap_idle, "grp_pqcrystals_dilithium_1_1_fu_107_ap_idle");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_ap_ready, "grp_pqcrystals_dilithium_1_1_fu_107_ap_ready");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sig_address0, "grp_pqcrystals_dilithium_1_1_fu_107_sig_address0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sig_ce0, "grp_pqcrystals_dilithium_1_1_fu_107_sig_ce0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sig_we0, "grp_pqcrystals_dilithium_1_1_fu_107_sig_we0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sig_d0, "grp_pqcrystals_dilithium_1_1_fu_107_sig_d0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sig_address1, "grp_pqcrystals_dilithium_1_1_fu_107_sig_address1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sig_ce1, "grp_pqcrystals_dilithium_1_1_fu_107_sig_ce1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sig_we1, "grp_pqcrystals_dilithium_1_1_fu_107_sig_we1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sig_d1, "grp_pqcrystals_dilithium_1_1_fu_107_sig_d1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sk_address0, "grp_pqcrystals_dilithium_1_1_fu_107_sk_address0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sk_ce0, "grp_pqcrystals_dilithium_1_1_fu_107_sk_ce0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sk_address1, "grp_pqcrystals_dilithium_1_1_fu_107_sk_address1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_sk_ce1, "grp_pqcrystals_dilithium_1_1_fu_107_sk_ce1");
    sc_trace(mVcdFile, i_0_reg_96, "i_0_reg_96");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_1_1_fu_107_ap_start_reg, "grp_pqcrystals_dilithium_1_1_fu_107_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln213_fu_164_p1, "zext_ln213_fu_164_p1");
    sc_trace(mVcdFile, zext_ln213_1_fu_180_p1, "zext_ln213_1_fu_180_p1");
    sc_trace(mVcdFile, trunc_ln213_fu_120_p1, "trunc_ln213_fu_120_p1");
    sc_trace(mVcdFile, trunc_ln213_1_fu_130_p1, "trunc_ln213_1_fu_130_p1");
    sc_trace(mVcdFile, trunc_ln212_1_fu_144_p1, "trunc_ln212_1_fu_144_p1");
    sc_trace(mVcdFile, sub_ln213_fu_159_p2, "sub_ln213_fu_159_p2");
    sc_trace(mVcdFile, trunc_ln212_fu_140_p1, "trunc_ln212_fu_140_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("pqcrystals_dilithium2_ref.hdltvin.dat");
    mHdltvoutHandle.open("pqcrystals_dilithium2_ref.hdltvout.dat");
}

pqcrystals_dilithium2_ref::~pqcrystals_dilithium2_ref() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_pqcrystals_dilithium_1_1_fu_107;
}

void pqcrystals_dilithium2_ref::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pqcrystals_dilithium_1_1_fu_107_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
             esl_seteq<1,1,1>(icmp_ln212_fu_148_p2.read(), ap_const_lv1_1))) {
            grp_pqcrystals_dilithium_1_1_fu_107_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pqcrystals_dilithium_1_1_fu_107_ap_ready.read())) {
            grp_pqcrystals_dilithium_1_1_fu_107_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_0_reg_96 = i_reg_204.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_96 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        add_ln213_1_reg_196 = add_ln213_1_fu_134_p2.read();
        add_ln213_reg_191 = add_ln213_fu_124_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_204 = i_fu_153_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln212_fu_148_p2.read(), ap_const_lv1_0))) {
        sub_ln213_1_reg_214 = sub_ln213_1_fu_169_p2.read();
    }
}

void pqcrystals_dilithium2_ref::thread_add_ln213_1_fu_134_p2() {
    add_ln213_1_fu_134_p2 = (!ap_const_lv14_973.is_01() || !trunc_ln213_1_fu_130_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_973) + sc_biguint<14>(trunc_ln213_1_fu_130_p1.read()));
}

void pqcrystals_dilithium2_ref::thread_add_ln213_fu_124_p2() {
    add_ln213_fu_124_p2 = (!ap_const_lv13_1FFF.is_01() || !trunc_ln213_fu_120_p1.read().is_01())? sc_lv<13>(): (sc_bigint<13>(ap_const_lv13_1FFF) + sc_biguint<13>(trunc_ln213_fu_120_p1.read()));
}

void pqcrystals_dilithium2_ref::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pqcrystals_dilithium2_ref::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pqcrystals_dilithium2_ref::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void pqcrystals_dilithium2_ref::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void pqcrystals_dilithium2_ref::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_pqcrystals_dilithium_1_1_fu_107_ap_done.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void pqcrystals_dilithium2_ref::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pqcrystals_dilithium2_ref::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(grp_pqcrystals_dilithium_1_1_fu_107_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pqcrystals_dilithium2_ref::thread_ap_return() {
    ap_return = ap_const_lv32_0;
}

void pqcrystals_dilithium2_ref::thread_grp_pqcrystals_dilithium_1_1_fu_107_ap_start() {
    grp_pqcrystals_dilithium_1_1_fu_107_ap_start = grp_pqcrystals_dilithium_1_1_fu_107_ap_start_reg.read();
}

void pqcrystals_dilithium2_ref::thread_i_fu_153_p2() {
    i_fu_153_p2 = (!ap_const_lv64_1.is_01() || !i_0_reg_96.read().is_01())? sc_lv<64>(): (sc_biguint<64>(ap_const_lv64_1) + sc_biguint<64>(i_0_reg_96.read()));
}

void pqcrystals_dilithium2_ref::thread_icmp_ln212_fu_148_p2() {
    icmp_ln212_fu_148_p2 = (!i_0_reg_96.read().is_01() || !mlen.read().is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_96.read() == mlen.read());
}

void pqcrystals_dilithium2_ref::thread_m_address0() {
    m_address0 =  (sc_lv<12>) (zext_ln213_fu_164_p1.read());
}

void pqcrystals_dilithium2_ref::thread_m_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        m_ce0 = ap_const_logic_1;
    } else {
        m_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium2_ref::thread_sk_address0() {
    sk_address0 = grp_pqcrystals_dilithium_1_1_fu_107_sk_address0.read();
}

void pqcrystals_dilithium2_ref::thread_sk_address1() {
    sk_address1 = grp_pqcrystals_dilithium_1_1_fu_107_sk_address1.read();
}

void pqcrystals_dilithium2_ref::thread_sk_ce0() {
    sk_ce0 = grp_pqcrystals_dilithium_1_1_fu_107_sk_ce0.read();
}

void pqcrystals_dilithium2_ref::thread_sk_ce1() {
    sk_ce1 = grp_pqcrystals_dilithium_1_1_fu_107_sk_ce1.read();
}

void pqcrystals_dilithium2_ref::thread_sm_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sm_address0 =  (sc_lv<13>) (zext_ln213_1_fu_180_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sm_address0 = grp_pqcrystals_dilithium_1_1_fu_107_sig_address0.read();
    } else {
        sm_address0 = "XXXXXXXXXXXXX";
    }
}

void pqcrystals_dilithium2_ref::thread_sm_address1() {
    sm_address1 = grp_pqcrystals_dilithium_1_1_fu_107_sig_address1.read();
}

void pqcrystals_dilithium2_ref::thread_sm_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sm_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sm_ce0 = grp_pqcrystals_dilithium_1_1_fu_107_sig_ce0.read();
    } else {
        sm_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium2_ref::thread_sm_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sm_ce1 = grp_pqcrystals_dilithium_1_1_fu_107_sig_ce1.read();
    } else {
        sm_ce1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium2_ref::thread_sm_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sm_d0 = m_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sm_d0 = grp_pqcrystals_dilithium_1_1_fu_107_sig_d0.read();
    } else {
        sm_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void pqcrystals_dilithium2_ref::thread_sm_d1() {
    sm_d1 = grp_pqcrystals_dilithium_1_1_fu_107_sig_d1.read();
}

void pqcrystals_dilithium2_ref::thread_sm_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sm_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sm_we0 = grp_pqcrystals_dilithium_1_1_fu_107_sig_we0.read();
    } else {
        sm_we0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium2_ref::thread_sm_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sm_we1 = grp_pqcrystals_dilithium_1_1_fu_107_sig_we1.read();
    } else {
        sm_we1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium2_ref::thread_smlen() {
    smlen = (!mlen.read().is_01() || !ap_const_lv64_974.is_01())? sc_lv<64>(): (sc_biguint<64>(mlen.read()) + sc_biguint<64>(ap_const_lv64_974));
}

void pqcrystals_dilithium2_ref::thread_smlen_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln212_fu_148_p2.read(), ap_const_lv1_1))) {
        smlen_ap_vld = ap_const_logic_1;
    } else {
        smlen_ap_vld = ap_const_logic_0;
    }
}

void pqcrystals_dilithium2_ref::thread_sub_ln213_1_fu_169_p2() {
    sub_ln213_1_fu_169_p2 = (!add_ln213_1_reg_196.read().is_01() || !trunc_ln212_fu_140_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln213_1_reg_196.read()) - sc_biguint<14>(trunc_ln212_fu_140_p1.read()));
}

void pqcrystals_dilithium2_ref::thread_sub_ln213_fu_159_p2() {
    sub_ln213_fu_159_p2 = (!add_ln213_reg_191.read().is_01() || !trunc_ln212_1_fu_144_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(add_ln213_reg_191.read()) - sc_biguint<13>(trunc_ln212_1_fu_144_p1.read()));
}

void pqcrystals_dilithium2_ref::thread_trunc_ln212_1_fu_144_p1() {
    trunc_ln212_1_fu_144_p1 = i_0_reg_96.read().range(13-1, 0);
}

void pqcrystals_dilithium2_ref::thread_trunc_ln212_fu_140_p1() {
    trunc_ln212_fu_140_p1 = i_0_reg_96.read().range(14-1, 0);
}

void pqcrystals_dilithium2_ref::thread_trunc_ln213_1_fu_130_p1() {
    trunc_ln213_1_fu_130_p1 = mlen.read().range(14-1, 0);
}

void pqcrystals_dilithium2_ref::thread_trunc_ln213_fu_120_p1() {
    trunc_ln213_fu_120_p1 = mlen.read().range(13-1, 0);
}

void pqcrystals_dilithium2_ref::thread_zext_ln213_1_fu_180_p1() {
    zext_ln213_1_fu_180_p1 = esl_zext<64,14>(sub_ln213_1_reg_214.read());
}

void pqcrystals_dilithium2_ref::thread_zext_ln213_fu_164_p1() {
    zext_ln213_fu_164_p1 = esl_zext<64,13>(sub_ln213_fu_159_p2.read());
}

void pqcrystals_dilithium2_ref::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln212_fu_148_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_pqcrystals_dilithium_1_1_fu_107_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

void pqcrystals_dilithium2_ref::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sm_address0\" :  \"" << sm_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sm_ce0\" :  \"" << sm_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sm_we0\" :  \"" << sm_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sm_d0\" :  \"" << sm_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sm_q0\" :  \"" << sm_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sm_address1\" :  \"" << sm_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sm_ce1\" :  \"" << sm_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sm_we1\" :  \"" << sm_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sm_d1\" :  \"" << sm_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sm_q1\" :  \"" << sm_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"smlen\" :  \"" << smlen.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"smlen_ap_vld\" :  \"" << smlen_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_address0\" :  \"" << m_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_ce0\" :  \"" << m_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_q0\" :  \"" << m_q0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"mlen\" :  \"" << mlen.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sk_address0\" :  \"" << sk_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sk_ce0\" :  \"" << sk_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sk_q0\" :  \"" << sk_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sk_address1\" :  \"" << sk_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sk_ce1\" :  \"" << sk_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sk_q1\" :  \"" << sk_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_return\" :  \"" << ap_return.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

