// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pqcrystals_dilithium_3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pqcrystals_dilithium_3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pqcrystals_dilithium_3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state1 = "1";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state2 = "10";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state3 = "100";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state4 = "1000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state5 = "10000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state6 = "100000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> pqcrystals_dilithium_3::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_2 = "10";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_9 = "1001";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_1 = "1";
const sc_lv<1> pqcrystals_dilithium_3::ap_const_lv1_0 = "0";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_3 = "11";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_4 = "100";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_5 = "101";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_7 = "111";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_8 = "1000";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_A = "1010";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_B = "1011";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_C = "1100";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_E = "1110";
const sc_lv<1> pqcrystals_dilithium_3::ap_const_lv1_1 = "1";
const sc_lv<9> pqcrystals_dilithium_3::ap_const_lv9_0 = "000000000";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_6 = "110";
const sc_lv<3> pqcrystals_dilithium_3::ap_const_lv3_1 = "1";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_D = "1101";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_F = "1111";
const sc_lv<8> pqcrystals_dilithium_3::ap_const_lv8_0 = "00000000";
const sc_lv<2> pqcrystals_dilithium_3::ap_const_lv2_0 = "00";
const sc_lv<9> pqcrystals_dilithium_3::ap_const_lv9_100 = "100000000";
const sc_lv<9> pqcrystals_dilithium_3::ap_const_lv9_1 = "1";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_3802001 = "11100000000010000000000001";
const sc_lv<55> pqcrystals_dilithium_3::ap_const_lv55_7FFFFFFF801FFF = "1111111111111111111111111111111100000000001111111111111";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_20 = "100000";
const sc_lv<32> pqcrystals_dilithium_3::ap_const_lv32_37 = "110111";
const sc_lv<3> pqcrystals_dilithium_3::ap_const_lv3_4 = "100";
const bool pqcrystals_dilithium_3::ap_const_boolean_1 = true;

pqcrystals_dilithium_3::pqcrystals_dilithium_3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    t_coeffs_U = new pqcrystals_dilithkbM("t_coeffs_U");
    t_coeffs_U->clk(ap_clk);
    t_coeffs_U->reset(ap_rst);
    t_coeffs_U->address0(t_coeffs_address0);
    t_coeffs_U->ce0(t_coeffs_ce0);
    t_coeffs_U->we0(t_coeffs_we0);
    t_coeffs_U->d0(t_coeffs_d0);
    t_coeffs_U->q0(t_coeffs_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln181_1_fu_338_p2);
    sensitive << ( zext_ln181_3_cast_reg_522 );
    sensitive << ( zext_ln181_8_fu_334_p1 );

    SC_METHOD(thread_add_ln181_2_fu_383_p2);
    sensitive << ( tmp_15_cast_reg_573 );
    sensitive << ( zext_ln181_10_fu_379_p1 );

    SC_METHOD(thread_add_ln181_3_fu_393_p2);
    sensitive << ( zext_ln176_reg_578 );
    sensitive << ( zext_ln181_9_fu_375_p1 );

    SC_METHOD(thread_add_ln181_fu_278_p2);
    sensitive << ( zext_ln181_3_reg_516 );
    sensitive << ( zext_ln181_5_fu_274_p1 );

    SC_METHOD(thread_add_ln19_1_fu_446_p2);
    sensitive << ( sext_ln181_4_fu_440_p1 );
    sensitive << ( sext_ln19_5_fu_443_p1 );

    SC_METHOD(thread_add_ln19_fu_307_p2);
    sensitive << ( sext_ln181_2_fu_301_p1 );
    sensitive << ( sext_ln19_2_fu_304_p1 );

    SC_METHOD(thread_add_ln88_1_fu_488_p2);
    sensitive << ( zext_ln181_3_reg_516 );
    sensitive << ( zext_ln88_1_fu_484_p1 );

    SC_METHOD(thread_add_ln88_fu_504_p2);
    sensitive << ( w_coeffs_q0 );
    sensitive << ( t_coeffs_q0 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln137_fu_328_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln137_fu_328_p2 );

    SC_METHOD(thread_i_7_fu_231_p2);
    sensitive << ( i_0_i_reg_146 );

    SC_METHOD(thread_i_8_fu_369_p2);
    sensitive << ( i_0_i1_reg_170 );

    SC_METHOD(thread_i_9_fu_473_p2);
    sensitive << ( i_0_i20_reg_182 );

    SC_METHOD(thread_i_fu_498_p2);
    sensitive << ( i_0_reg_158 );

    SC_METHOD(thread_icmp_ln137_fu_328_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( i_0_reg_158 );

    SC_METHOD(thread_icmp_ln180_1_fu_363_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i_0_i1_reg_170 );

    SC_METHOD(thread_icmp_ln180_fu_225_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_i_reg_146 );

    SC_METHOD(thread_icmp_ln87_fu_467_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( i_0_i20_reg_182 );

    SC_METHOD(thread_mul_ln181_1_fu_411_p0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( mul_ln181_1_fu_411_p00 );

    SC_METHOD(thread_mul_ln181_1_fu_411_p00);
    sensitive << ( reg_193 );

    SC_METHOD(thread_mul_ln181_1_fu_411_p1);
    sensitive << ( reg_197 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_mul_ln181_1_fu_411_p2);
    sensitive << ( mul_ln181_1_fu_411_p0 );
    sensitive << ( mul_ln181_1_fu_411_p1 );

    SC_METHOD(thread_mul_ln181_fu_264_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( mul_ln181_fu_264_p00 );

    SC_METHOD(thread_mul_ln181_fu_264_p00);
    sensitive << ( reg_193 );

    SC_METHOD(thread_mul_ln181_fu_264_p1);
    sensitive << ( reg_197 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_mul_ln181_fu_264_p2);
    sensitive << ( mul_ln181_fu_264_p0 );
    sensitive << ( mul_ln181_fu_264_p1 );

    SC_METHOD(thread_mul_ln19_1_fu_429_p1);
    sensitive << ( t_5_reg_611 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_mul_ln19_1_fu_429_p2);
    sensitive << ( mul_ln19_1_fu_429_p1 );

    SC_METHOD(thread_mul_ln19_fu_291_p1);
    sensitive << ( t_reg_560 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_mul_ln19_fu_291_p2);
    sensitive << ( mul_ln19_fu_291_p1 );

    SC_METHOD(thread_sext_ln181_2_fu_301_p1);
    sensitive << ( mul_ln181_reg_545 );

    SC_METHOD(thread_sext_ln181_4_fu_440_p1);
    sensitive << ( mul_ln181_1_reg_601 );

    SC_METHOD(thread_sext_ln19_2_fu_304_p1);
    sensitive << ( mul_ln19_reg_565 );

    SC_METHOD(thread_sext_ln19_5_fu_443_p1);
    sensitive << ( mul_ln19_1_reg_616 );

    SC_METHOD(thread_t_4_fu_323_p1);
    sensitive << ( tmp_3_fu_313_p4 );

    SC_METHOD(thread_t_5_fu_421_p2);
    sensitive << ( trunc_ln18_1_reg_606 );

    SC_METHOD(thread_t_coeffs_address0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( zext_ln181_1_fu_435_p1 );
    sensitive << ( zext_ln88_fu_479_p1 );

    SC_METHOD(thread_t_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_t_coeffs_d0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( tmp_4_fu_452_p4 );

    SC_METHOD(thread_t_coeffs_we0);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_t_fu_283_p2);
    sensitive << ( trunc_ln18_reg_550 );

    SC_METHOD(thread_tmp_15_cast_fu_343_p3);
    sensitive << ( add_ln181_1_fu_338_p2 );

    SC_METHOD(thread_tmp_1_fu_242_p4);
    sensitive << ( w_coeffs_offset );
    sensitive << ( i_0_i_reg_146 );

    SC_METHOD(thread_tmp_2_fu_351_p3);
    sensitive << ( i_0_reg_158 );

    SC_METHOD(thread_tmp_3_fu_313_p4);
    sensitive << ( add_ln19_fu_307_p2 );

    SC_METHOD(thread_tmp_4_fu_452_p4);
    sensitive << ( add_ln19_1_fu_446_p2 );

    SC_METHOD(thread_tmp_fu_201_p3);
    sensitive << ( w_coeffs_offset );

    SC_METHOD(thread_tmp_s_fu_213_p3);
    sensitive << ( w_coeffs_offset );

    SC_METHOD(thread_trunc_ln18_1_fu_417_p1);
    sensitive << ( mul_ln181_1_fu_411_p2 );

    SC_METHOD(thread_trunc_ln18_fu_270_p1);
    sensitive << ( mul_ln181_fu_264_p2 );

    SC_METHOD(thread_u_vec_coeffs_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln181_4_fu_251_p1 );
    sensitive << ( zext_ln181_11_fu_388_p1 );

    SC_METHOD(thread_u_vec_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_v_vec_coeffs_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln181_fu_237_p1 );
    sensitive << ( zext_ln181_12_fu_398_p1 );

    SC_METHOD(thread_v_vec_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_w_coeffs_address0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( w_coeffs_addr_1_reg_629 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( zext_ln181_6_fu_297_p1 );
    sensitive << ( zext_ln88_2_fu_493_p1 );

    SC_METHOD(thread_w_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_w_coeffs_d0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( t_4_fu_323_p1 );
    sensitive << ( add_ln88_fu_504_p2 );

    SC_METHOD(thread_w_coeffs_we0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_zext_ln176_fu_359_p1);
    sensitive << ( tmp_2_fu_351_p3 );

    SC_METHOD(thread_zext_ln181_10_fu_379_p1);
    sensitive << ( i_0_i1_reg_170 );

    SC_METHOD(thread_zext_ln181_11_fu_388_p1);
    sensitive << ( add_ln181_2_fu_383_p2 );

    SC_METHOD(thread_zext_ln181_12_fu_398_p1);
    sensitive << ( add_ln181_3_fu_393_p2 );

    SC_METHOD(thread_zext_ln181_1_fu_435_p1);
    sensitive << ( i_0_i1_reg_170 );

    SC_METHOD(thread_zext_ln181_3_cast_fu_221_p1);
    sensitive << ( tmp_s_fu_213_p3 );

    SC_METHOD(thread_zext_ln181_3_fu_209_p1);
    sensitive << ( tmp_fu_201_p3 );

    SC_METHOD(thread_zext_ln181_4_fu_251_p1);
    sensitive << ( tmp_1_fu_242_p4 );

    SC_METHOD(thread_zext_ln181_5_fu_274_p1);
    sensitive << ( i_0_i_reg_146 );

    SC_METHOD(thread_zext_ln181_6_fu_297_p1);
    sensitive << ( add_ln181_reg_555 );

    SC_METHOD(thread_zext_ln181_8_fu_334_p1);
    sensitive << ( i_0_reg_158 );

    SC_METHOD(thread_zext_ln181_9_fu_375_p1);
    sensitive << ( i_0_i1_reg_170 );

    SC_METHOD(thread_zext_ln181_fu_237_p1);
    sensitive << ( i_0_i_reg_146 );

    SC_METHOD(thread_zext_ln88_1_fu_484_p1);
    sensitive << ( i_0_i20_reg_182 );

    SC_METHOD(thread_zext_ln88_2_fu_493_p1);
    sensitive << ( add_ln88_1_fu_488_p2 );

    SC_METHOD(thread_zext_ln88_fu_479_p1);
    sensitive << ( i_0_i20_reg_182 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln180_fu_225_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln137_fu_328_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln180_1_fu_363_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( icmp_ln87_fu_467_p2 );

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pqcrystals_dilithium_3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, w_coeffs_address0, "(port)w_coeffs_address0");
    sc_trace(mVcdFile, w_coeffs_ce0, "(port)w_coeffs_ce0");
    sc_trace(mVcdFile, w_coeffs_we0, "(port)w_coeffs_we0");
    sc_trace(mVcdFile, w_coeffs_d0, "(port)w_coeffs_d0");
    sc_trace(mVcdFile, w_coeffs_q0, "(port)w_coeffs_q0");
    sc_trace(mVcdFile, w_coeffs_offset, "(port)w_coeffs_offset");
    sc_trace(mVcdFile, u_vec_coeffs_address0, "(port)u_vec_coeffs_address0");
    sc_trace(mVcdFile, u_vec_coeffs_ce0, "(port)u_vec_coeffs_ce0");
    sc_trace(mVcdFile, u_vec_coeffs_q0, "(port)u_vec_coeffs_q0");
    sc_trace(mVcdFile, v_vec_coeffs_address0, "(port)v_vec_coeffs_address0");
    sc_trace(mVcdFile, v_vec_coeffs_ce0, "(port)v_vec_coeffs_ce0");
    sc_trace(mVcdFile, v_vec_coeffs_q0, "(port)v_vec_coeffs_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_193, "reg_193");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, reg_197, "reg_197");
    sc_trace(mVcdFile, zext_ln181_3_fu_209_p1, "zext_ln181_3_fu_209_p1");
    sc_trace(mVcdFile, zext_ln181_3_reg_516, "zext_ln181_3_reg_516");
    sc_trace(mVcdFile, zext_ln181_3_cast_fu_221_p1, "zext_ln181_3_cast_fu_221_p1");
    sc_trace(mVcdFile, zext_ln181_3_cast_reg_522, "zext_ln181_3_cast_reg_522");
    sc_trace(mVcdFile, i_7_fu_231_p2, "i_7_fu_231_p2");
    sc_trace(mVcdFile, i_7_reg_530, "i_7_reg_530");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln180_fu_225_p2, "icmp_ln180_fu_225_p2");
    sc_trace(mVcdFile, mul_ln181_fu_264_p2, "mul_ln181_fu_264_p2");
    sc_trace(mVcdFile, mul_ln181_reg_545, "mul_ln181_reg_545");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, trunc_ln18_fu_270_p1, "trunc_ln18_fu_270_p1");
    sc_trace(mVcdFile, trunc_ln18_reg_550, "trunc_ln18_reg_550");
    sc_trace(mVcdFile, add_ln181_fu_278_p2, "add_ln181_fu_278_p2");
    sc_trace(mVcdFile, add_ln181_reg_555, "add_ln181_reg_555");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, t_fu_283_p2, "t_fu_283_p2");
    sc_trace(mVcdFile, t_reg_560, "t_reg_560");
    sc_trace(mVcdFile, mul_ln19_fu_291_p2, "mul_ln19_fu_291_p2");
    sc_trace(mVcdFile, mul_ln19_reg_565, "mul_ln19_reg_565");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_15_cast_fu_343_p3, "tmp_15_cast_fu_343_p3");
    sc_trace(mVcdFile, tmp_15_cast_reg_573, "tmp_15_cast_reg_573");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, icmp_ln137_fu_328_p2, "icmp_ln137_fu_328_p2");
    sc_trace(mVcdFile, zext_ln176_fu_359_p1, "zext_ln176_fu_359_p1");
    sc_trace(mVcdFile, zext_ln176_reg_578, "zext_ln176_reg_578");
    sc_trace(mVcdFile, i_8_fu_369_p2, "i_8_fu_369_p2");
    sc_trace(mVcdFile, i_8_reg_586, "i_8_reg_586");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, icmp_ln180_1_fu_363_p2, "icmp_ln180_1_fu_363_p2");
    sc_trace(mVcdFile, mul_ln181_1_fu_411_p2, "mul_ln181_1_fu_411_p2");
    sc_trace(mVcdFile, mul_ln181_1_reg_601, "mul_ln181_1_reg_601");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, trunc_ln18_1_fu_417_p1, "trunc_ln18_1_fu_417_p1");
    sc_trace(mVcdFile, trunc_ln18_1_reg_606, "trunc_ln18_1_reg_606");
    sc_trace(mVcdFile, t_5_fu_421_p2, "t_5_fu_421_p2");
    sc_trace(mVcdFile, t_5_reg_611, "t_5_reg_611");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, mul_ln19_1_fu_429_p2, "mul_ln19_1_fu_429_p2");
    sc_trace(mVcdFile, mul_ln19_1_reg_616, "mul_ln19_1_reg_616");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, i_9_fu_473_p2, "i_9_fu_473_p2");
    sc_trace(mVcdFile, i_9_reg_624, "i_9_reg_624");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, w_coeffs_addr_1_reg_629, "w_coeffs_addr_1_reg_629");
    sc_trace(mVcdFile, icmp_ln87_fu_467_p2, "icmp_ln87_fu_467_p2");
    sc_trace(mVcdFile, i_fu_498_p2, "i_fu_498_p2");
    sc_trace(mVcdFile, t_coeffs_address0, "t_coeffs_address0");
    sc_trace(mVcdFile, t_coeffs_ce0, "t_coeffs_ce0");
    sc_trace(mVcdFile, t_coeffs_we0, "t_coeffs_we0");
    sc_trace(mVcdFile, t_coeffs_d0, "t_coeffs_d0");
    sc_trace(mVcdFile, t_coeffs_q0, "t_coeffs_q0");
    sc_trace(mVcdFile, i_0_i_reg_146, "i_0_i_reg_146");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_0_reg_158, "i_0_reg_158");
    sc_trace(mVcdFile, i_0_i1_reg_170, "i_0_i1_reg_170");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, i_0_i20_reg_182, "i_0_i20_reg_182");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, zext_ln181_4_fu_251_p1, "zext_ln181_4_fu_251_p1");
    sc_trace(mVcdFile, zext_ln181_fu_237_p1, "zext_ln181_fu_237_p1");
    sc_trace(mVcdFile, zext_ln181_6_fu_297_p1, "zext_ln181_6_fu_297_p1");
    sc_trace(mVcdFile, zext_ln181_11_fu_388_p1, "zext_ln181_11_fu_388_p1");
    sc_trace(mVcdFile, zext_ln181_12_fu_398_p1, "zext_ln181_12_fu_398_p1");
    sc_trace(mVcdFile, zext_ln181_1_fu_435_p1, "zext_ln181_1_fu_435_p1");
    sc_trace(mVcdFile, zext_ln88_2_fu_493_p1, "zext_ln88_2_fu_493_p1");
    sc_trace(mVcdFile, zext_ln88_fu_479_p1, "zext_ln88_fu_479_p1");
    sc_trace(mVcdFile, t_4_fu_323_p1, "t_4_fu_323_p1");
    sc_trace(mVcdFile, add_ln88_fu_504_p2, "add_ln88_fu_504_p2");
    sc_trace(mVcdFile, tmp_fu_201_p3, "tmp_fu_201_p3");
    sc_trace(mVcdFile, tmp_s_fu_213_p3, "tmp_s_fu_213_p3");
    sc_trace(mVcdFile, tmp_1_fu_242_p4, "tmp_1_fu_242_p4");
    sc_trace(mVcdFile, mul_ln181_fu_264_p0, "mul_ln181_fu_264_p0");
    sc_trace(mVcdFile, mul_ln181_fu_264_p1, "mul_ln181_fu_264_p1");
    sc_trace(mVcdFile, zext_ln181_5_fu_274_p1, "zext_ln181_5_fu_274_p1");
    sc_trace(mVcdFile, mul_ln19_fu_291_p1, "mul_ln19_fu_291_p1");
    sc_trace(mVcdFile, sext_ln181_2_fu_301_p1, "sext_ln181_2_fu_301_p1");
    sc_trace(mVcdFile, sext_ln19_2_fu_304_p1, "sext_ln19_2_fu_304_p1");
    sc_trace(mVcdFile, add_ln19_fu_307_p2, "add_ln19_fu_307_p2");
    sc_trace(mVcdFile, tmp_3_fu_313_p4, "tmp_3_fu_313_p4");
    sc_trace(mVcdFile, zext_ln181_8_fu_334_p1, "zext_ln181_8_fu_334_p1");
    sc_trace(mVcdFile, add_ln181_1_fu_338_p2, "add_ln181_1_fu_338_p2");
    sc_trace(mVcdFile, tmp_2_fu_351_p3, "tmp_2_fu_351_p3");
    sc_trace(mVcdFile, zext_ln181_10_fu_379_p1, "zext_ln181_10_fu_379_p1");
    sc_trace(mVcdFile, add_ln181_2_fu_383_p2, "add_ln181_2_fu_383_p2");
    sc_trace(mVcdFile, zext_ln181_9_fu_375_p1, "zext_ln181_9_fu_375_p1");
    sc_trace(mVcdFile, add_ln181_3_fu_393_p2, "add_ln181_3_fu_393_p2");
    sc_trace(mVcdFile, mul_ln181_1_fu_411_p0, "mul_ln181_1_fu_411_p0");
    sc_trace(mVcdFile, mul_ln181_1_fu_411_p1, "mul_ln181_1_fu_411_p1");
    sc_trace(mVcdFile, mul_ln19_1_fu_429_p1, "mul_ln19_1_fu_429_p1");
    sc_trace(mVcdFile, sext_ln181_4_fu_440_p1, "sext_ln181_4_fu_440_p1");
    sc_trace(mVcdFile, sext_ln19_5_fu_443_p1, "sext_ln19_5_fu_443_p1");
    sc_trace(mVcdFile, add_ln19_1_fu_446_p2, "add_ln19_1_fu_446_p2");
    sc_trace(mVcdFile, tmp_4_fu_452_p4, "tmp_4_fu_452_p4");
    sc_trace(mVcdFile, zext_ln88_1_fu_484_p1, "zext_ln88_1_fu_484_p1");
    sc_trace(mVcdFile, add_ln88_1_fu_488_p2, "add_ln88_1_fu_488_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln181_1_fu_411_p00, "mul_ln181_1_fu_411_p00");
    sc_trace(mVcdFile, mul_ln181_fu_264_p00, "mul_ln181_fu_264_p00");
#endif

    }
}

pqcrystals_dilithium_3::~pqcrystals_dilithium_3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete t_coeffs_U;
}

void pqcrystals_dilithium_3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        i_0_i1_reg_170 = i_8_reg_586.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln137_fu_328_p2.read()))) {
        i_0_i1_reg_170 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(icmp_ln180_1_fu_363_p2.read(), ap_const_lv1_1))) {
        i_0_i20_reg_182 = ap_const_lv9_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        i_0_i20_reg_182 = i_9_reg_624.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i_0_i_reg_146 = i_7_reg_530.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_i_reg_146 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln180_fu_225_p2.read(), ap_const_lv1_1))) {
        i_0_reg_158 = ap_const_lv3_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(icmp_ln87_fu_467_p2.read(), ap_const_lv1_1))) {
        i_0_reg_158 = i_fu_498_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        add_ln181_reg_555 = add_ln181_fu_278_p2.read();
        t_reg_560 = t_fu_283_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_7_reg_530 = i_7_fu_231_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_8_reg_586 = i_8_fu_369_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i_9_reg_624 = i_9_fu_473_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        mul_ln181_1_reg_601 = mul_ln181_1_fu_411_p2.read();
        trunc_ln18_1_reg_606 = trunc_ln18_1_fu_417_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        mul_ln181_reg_545 = mul_ln181_fu_264_p2.read();
        trunc_ln18_reg_550 = trunc_ln18_fu_270_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        mul_ln19_1_reg_616 = mul_ln19_1_fu_429_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        mul_ln19_reg_565 = mul_ln19_fu_291_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        reg_193 = u_vec_coeffs_q0.read();
        reg_197 = v_vec_coeffs_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        t_5_reg_611 = t_5_fu_421_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln137_fu_328_p2.read()))) {
        tmp_15_cast_reg_573 = tmp_15_cast_fu_343_p3.read();
        zext_ln176_reg_578 = zext_ln176_fu_359_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln87_fu_467_p2.read()))) {
        w_coeffs_addr_1_reg_629 =  (sc_lv<10>) (zext_ln88_2_fu_493_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        zext_ln181_3_cast_reg_522 = zext_ln181_3_cast_fu_221_p1.read();
        zext_ln181_3_reg_516 = zext_ln181_3_fu_209_p1.read();
    }
}

void pqcrystals_dilithium_3::thread_add_ln181_1_fu_338_p2() {
    add_ln181_1_fu_338_p2 = (!zext_ln181_8_fu_334_p1.read().is_01() || !zext_ln181_3_cast_reg_522.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln181_8_fu_334_p1.read()) + sc_biguint<6>(zext_ln181_3_cast_reg_522.read()));
}

void pqcrystals_dilithium_3::thread_add_ln181_2_fu_383_p2() {
    add_ln181_2_fu_383_p2 = (!tmp_15_cast_reg_573.read().is_01() || !zext_ln181_10_fu_379_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_15_cast_reg_573.read()) + sc_biguint<14>(zext_ln181_10_fu_379_p1.read()));
}

void pqcrystals_dilithium_3::thread_add_ln181_3_fu_393_p2() {
    add_ln181_3_fu_393_p2 = (!zext_ln176_reg_578.read().is_01() || !zext_ln181_9_fu_375_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln176_reg_578.read()) + sc_biguint<12>(zext_ln181_9_fu_375_p1.read()));
}

void pqcrystals_dilithium_3::thread_add_ln181_fu_278_p2() {
    add_ln181_fu_278_p2 = (!zext_ln181_3_reg_516.read().is_01() || !zext_ln181_5_fu_274_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln181_3_reg_516.read()) + sc_biguint<12>(zext_ln181_5_fu_274_p1.read()));
}

void pqcrystals_dilithium_3::thread_add_ln19_1_fu_446_p2() {
    add_ln19_1_fu_446_p2 = (!sext_ln181_4_fu_440_p1.read().is_01() || !sext_ln19_5_fu_443_p1.read().is_01())? sc_lv<56>(): (sc_bigint<56>(sext_ln181_4_fu_440_p1.read()) + sc_bigint<56>(sext_ln19_5_fu_443_p1.read()));
}

void pqcrystals_dilithium_3::thread_add_ln19_fu_307_p2() {
    add_ln19_fu_307_p2 = (!sext_ln181_2_fu_301_p1.read().is_01() || !sext_ln19_2_fu_304_p1.read().is_01())? sc_lv<56>(): (sc_bigint<56>(sext_ln181_2_fu_301_p1.read()) + sc_bigint<56>(sext_ln19_2_fu_304_p1.read()));
}

void pqcrystals_dilithium_3::thread_add_ln88_1_fu_488_p2() {
    add_ln88_1_fu_488_p2 = (!zext_ln181_3_reg_516.read().is_01() || !zext_ln88_1_fu_484_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln181_3_reg_516.read()) + sc_biguint<12>(zext_ln88_1_fu_484_p1.read()));
}

void pqcrystals_dilithium_3::thread_add_ln88_fu_504_p2() {
    add_ln88_fu_504_p2 = (!w_coeffs_q0.read().is_01() || !t_coeffs_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(w_coeffs_q0.read()) + sc_biguint<32>(t_coeffs_q0.read()));
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void pqcrystals_dilithium_3::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void pqcrystals_dilithium_3::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(icmp_ln137_fu_328_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln137_fu_328_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_3::thread_i_7_fu_231_p2() {
    i_7_fu_231_p2 = (!i_0_i_reg_146.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_0_i_reg_146.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void pqcrystals_dilithium_3::thread_i_8_fu_369_p2() {
    i_8_fu_369_p2 = (!i_0_i1_reg_170.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_0_i1_reg_170.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void pqcrystals_dilithium_3::thread_i_9_fu_473_p2() {
    i_9_fu_473_p2 = (!i_0_i20_reg_182.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_0_i20_reg_182.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void pqcrystals_dilithium_3::thread_i_fu_498_p2() {
    i_fu_498_p2 = (!i_0_reg_158.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_0_reg_158.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void pqcrystals_dilithium_3::thread_icmp_ln137_fu_328_p2() {
    icmp_ln137_fu_328_p2 = (!i_0_reg_158.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_158.read() == ap_const_lv3_4);
}

void pqcrystals_dilithium_3::thread_icmp_ln180_1_fu_363_p2() {
    icmp_ln180_1_fu_363_p2 = (!i_0_i1_reg_170.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i1_reg_170.read() == ap_const_lv9_100);
}

void pqcrystals_dilithium_3::thread_icmp_ln180_fu_225_p2() {
    icmp_ln180_fu_225_p2 = (!i_0_i_reg_146.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_146.read() == ap_const_lv9_100);
}

void pqcrystals_dilithium_3::thread_icmp_ln87_fu_467_p2() {
    icmp_ln87_fu_467_p2 = (!i_0_i20_reg_182.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i20_reg_182.read() == ap_const_lv9_100);
}

void pqcrystals_dilithium_3::thread_mul_ln181_1_fu_411_p0() {
    mul_ln181_1_fu_411_p0 =  (sc_lv<23>) (mul_ln181_1_fu_411_p00.read());
}

void pqcrystals_dilithium_3::thread_mul_ln181_1_fu_411_p00() {
    mul_ln181_1_fu_411_p00 = esl_zext<55,23>(reg_193.read());
}

void pqcrystals_dilithium_3::thread_mul_ln181_1_fu_411_p1() {
    mul_ln181_1_fu_411_p1 = reg_197.read();
}

void pqcrystals_dilithium_3::thread_mul_ln181_1_fu_411_p2() {
    mul_ln181_1_fu_411_p2 = (!mul_ln181_1_fu_411_p0.read().is_01() || !mul_ln181_1_fu_411_p1.read().is_01())? sc_lv<55>(): sc_biguint<23>(mul_ln181_1_fu_411_p0.read()) * sc_bigint<32>(mul_ln181_1_fu_411_p1.read());
}

void pqcrystals_dilithium_3::thread_mul_ln181_fu_264_p0() {
    mul_ln181_fu_264_p0 =  (sc_lv<23>) (mul_ln181_fu_264_p00.read());
}

void pqcrystals_dilithium_3::thread_mul_ln181_fu_264_p00() {
    mul_ln181_fu_264_p00 = esl_zext<55,23>(reg_193.read());
}

void pqcrystals_dilithium_3::thread_mul_ln181_fu_264_p1() {
    mul_ln181_fu_264_p1 = reg_197.read();
}

void pqcrystals_dilithium_3::thread_mul_ln181_fu_264_p2() {
    mul_ln181_fu_264_p2 = (!mul_ln181_fu_264_p0.read().is_01() || !mul_ln181_fu_264_p1.read().is_01())? sc_lv<55>(): sc_biguint<23>(mul_ln181_fu_264_p0.read()) * sc_bigint<32>(mul_ln181_fu_264_p1.read());
}

void pqcrystals_dilithium_3::thread_mul_ln19_1_fu_429_p1() {
    mul_ln19_1_fu_429_p1 = t_5_reg_611.read();
}

void pqcrystals_dilithium_3::thread_mul_ln19_1_fu_429_p2() {
    mul_ln19_1_fu_429_p2 = (!ap_const_lv55_7FFFFFFF801FFF.is_01() || !mul_ln19_1_fu_429_p1.read().is_01())? sc_lv<55>(): sc_bigint<55>(ap_const_lv55_7FFFFFFF801FFF) * sc_bigint<32>(mul_ln19_1_fu_429_p1.read());
}

void pqcrystals_dilithium_3::thread_mul_ln19_fu_291_p1() {
    mul_ln19_fu_291_p1 = t_reg_560.read();
}

void pqcrystals_dilithium_3::thread_mul_ln19_fu_291_p2() {
    mul_ln19_fu_291_p2 = (!ap_const_lv55_7FFFFFFF801FFF.is_01() || !mul_ln19_fu_291_p1.read().is_01())? sc_lv<55>(): sc_bigint<55>(ap_const_lv55_7FFFFFFF801FFF) * sc_bigint<32>(mul_ln19_fu_291_p1.read());
}

void pqcrystals_dilithium_3::thread_sext_ln181_2_fu_301_p1() {
    sext_ln181_2_fu_301_p1 = esl_sext<56,55>(mul_ln181_reg_545.read());
}

void pqcrystals_dilithium_3::thread_sext_ln181_4_fu_440_p1() {
    sext_ln181_4_fu_440_p1 = esl_sext<56,55>(mul_ln181_1_reg_601.read());
}

void pqcrystals_dilithium_3::thread_sext_ln19_2_fu_304_p1() {
    sext_ln19_2_fu_304_p1 = esl_sext<56,55>(mul_ln19_reg_565.read());
}

void pqcrystals_dilithium_3::thread_sext_ln19_5_fu_443_p1() {
    sext_ln19_5_fu_443_p1 = esl_sext<56,55>(mul_ln19_1_reg_616.read());
}

void pqcrystals_dilithium_3::thread_t_4_fu_323_p1() {
    t_4_fu_323_p1 = esl_sext<32,24>(tmp_3_fu_313_p4.read());
}

void pqcrystals_dilithium_3::thread_t_5_fu_421_p2() {
    t_5_fu_421_p2 = (!ap_const_lv32_3802001.is_01() || !trunc_ln18_1_reg_606.read().is_01())? sc_lv<32>(): sc_biguint<32>(ap_const_lv32_3802001) * sc_bigint<32>(trunc_ln18_1_reg_606.read());
}

void pqcrystals_dilithium_3::thread_t_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        t_coeffs_address0 =  (sc_lv<8>) (zext_ln88_fu_479_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        t_coeffs_address0 =  (sc_lv<8>) (zext_ln181_1_fu_435_p1.read());
    } else {
        t_coeffs_address0 = "XXXXXXXX";
    }
}

void pqcrystals_dilithium_3::thread_t_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        t_coeffs_ce0 = ap_const_logic_1;
    } else {
        t_coeffs_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_3::thread_t_coeffs_d0() {
    t_coeffs_d0 = esl_sext<32,24>(tmp_4_fu_452_p4.read());
}

void pqcrystals_dilithium_3::thread_t_coeffs_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        t_coeffs_we0 = ap_const_logic_1;
    } else {
        t_coeffs_we0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_3::thread_t_fu_283_p2() {
    t_fu_283_p2 = (!ap_const_lv32_3802001.is_01() || !trunc_ln18_reg_550.read().is_01())? sc_lv<32>(): sc_biguint<32>(ap_const_lv32_3802001) * sc_bigint<32>(trunc_ln18_reg_550.read());
}

void pqcrystals_dilithium_3::thread_tmp_15_cast_fu_343_p3() {
    tmp_15_cast_fu_343_p3 = esl_concat<6,8>(add_ln181_1_fu_338_p2.read(), ap_const_lv8_0);
}

void pqcrystals_dilithium_3::thread_tmp_1_fu_242_p4() {
    tmp_1_fu_242_p4 = esl_concat<4,9>(esl_concat<3,1>(w_coeffs_offset.read(), ap_const_lv1_0), i_0_i_reg_146.read());
}

void pqcrystals_dilithium_3::thread_tmp_2_fu_351_p3() {
    tmp_2_fu_351_p3 = esl_concat<3,8>(i_0_reg_158.read(), ap_const_lv8_0);
}

void pqcrystals_dilithium_3::thread_tmp_3_fu_313_p4() {
    tmp_3_fu_313_p4 = add_ln19_fu_307_p2.read().range(55, 32);
}

void pqcrystals_dilithium_3::thread_tmp_4_fu_452_p4() {
    tmp_4_fu_452_p4 = add_ln19_1_fu_446_p2.read().range(55, 32);
}

void pqcrystals_dilithium_3::thread_tmp_fu_201_p3() {
    tmp_fu_201_p3 = esl_concat<3,8>(w_coeffs_offset.read(), ap_const_lv8_0);
}

void pqcrystals_dilithium_3::thread_tmp_s_fu_213_p3() {
    tmp_s_fu_213_p3 = esl_concat<3,2>(w_coeffs_offset.read(), ap_const_lv2_0);
}

void pqcrystals_dilithium_3::thread_trunc_ln18_1_fu_417_p1() {
    trunc_ln18_1_fu_417_p1 = mul_ln181_1_fu_411_p2.read().range(32-1, 0);
}

void pqcrystals_dilithium_3::thread_trunc_ln18_fu_270_p1() {
    trunc_ln18_fu_270_p1 = mul_ln181_fu_264_p2.read().range(32-1, 0);
}

void pqcrystals_dilithium_3::thread_u_vec_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        u_vec_coeffs_address0 =  (sc_lv<12>) (zext_ln181_11_fu_388_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        u_vec_coeffs_address0 =  (sc_lv<12>) (zext_ln181_4_fu_251_p1.read());
    } else {
        u_vec_coeffs_address0 =  (sc_lv<12>) ("XXXXXXXXXXXX");
    }
}

void pqcrystals_dilithium_3::thread_u_vec_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        u_vec_coeffs_ce0 = ap_const_logic_1;
    } else {
        u_vec_coeffs_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_3::thread_v_vec_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        v_vec_coeffs_address0 =  (sc_lv<10>) (zext_ln181_12_fu_398_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        v_vec_coeffs_address0 =  (sc_lv<10>) (zext_ln181_fu_237_p1.read());
    } else {
        v_vec_coeffs_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void pqcrystals_dilithium_3::thread_v_vec_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        v_vec_coeffs_ce0 = ap_const_logic_1;
    } else {
        v_vec_coeffs_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_3::thread_w_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        w_coeffs_address0 = w_coeffs_addr_1_reg_629.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        w_coeffs_address0 =  (sc_lv<10>) (zext_ln88_2_fu_493_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        w_coeffs_address0 =  (sc_lv<10>) (zext_ln181_6_fu_297_p1.read());
    } else {
        w_coeffs_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void pqcrystals_dilithium_3::thread_w_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        w_coeffs_ce0 = ap_const_logic_1;
    } else {
        w_coeffs_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_3::thread_w_coeffs_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        w_coeffs_d0 = add_ln88_fu_504_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        w_coeffs_d0 = t_4_fu_323_p1.read();
    } else {
        w_coeffs_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void pqcrystals_dilithium_3::thread_w_coeffs_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        w_coeffs_we0 = ap_const_logic_1;
    } else {
        w_coeffs_we0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_3::thread_zext_ln176_fu_359_p1() {
    zext_ln176_fu_359_p1 = esl_zext<12,11>(tmp_2_fu_351_p3.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_10_fu_379_p1() {
    zext_ln181_10_fu_379_p1 = esl_zext<14,9>(i_0_i1_reg_170.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_11_fu_388_p1() {
    zext_ln181_11_fu_388_p1 = esl_zext<64,14>(add_ln181_2_fu_383_p2.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_12_fu_398_p1() {
    zext_ln181_12_fu_398_p1 = esl_zext<64,12>(add_ln181_3_fu_393_p2.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_1_fu_435_p1() {
    zext_ln181_1_fu_435_p1 = esl_zext<64,9>(i_0_i1_reg_170.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_3_cast_fu_221_p1() {
    zext_ln181_3_cast_fu_221_p1 = esl_zext<6,5>(tmp_s_fu_213_p3.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_3_fu_209_p1() {
    zext_ln181_3_fu_209_p1 = esl_zext<12,11>(tmp_fu_201_p3.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_4_fu_251_p1() {
    zext_ln181_4_fu_251_p1 = esl_zext<64,13>(tmp_1_fu_242_p4.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_5_fu_274_p1() {
    zext_ln181_5_fu_274_p1 = esl_zext<12,9>(i_0_i_reg_146.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_6_fu_297_p1() {
    zext_ln181_6_fu_297_p1 = esl_zext<64,12>(add_ln181_reg_555.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_8_fu_334_p1() {
    zext_ln181_8_fu_334_p1 = esl_zext<6,3>(i_0_reg_158.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_9_fu_375_p1() {
    zext_ln181_9_fu_375_p1 = esl_zext<12,9>(i_0_i1_reg_170.read());
}

void pqcrystals_dilithium_3::thread_zext_ln181_fu_237_p1() {
    zext_ln181_fu_237_p1 = esl_zext<64,9>(i_0_i_reg_146.read());
}

void pqcrystals_dilithium_3::thread_zext_ln88_1_fu_484_p1() {
    zext_ln88_1_fu_484_p1 = esl_zext<12,9>(i_0_i20_reg_182.read());
}

void pqcrystals_dilithium_3::thread_zext_ln88_2_fu_493_p1() {
    zext_ln88_2_fu_493_p1 = esl_zext<64,12>(add_ln88_1_fu_488_p2.read());
}

void pqcrystals_dilithium_3::thread_zext_ln88_fu_479_p1() {
    zext_ln88_fu_479_p1 = esl_zext<64,9>(i_0_i20_reg_182.read());
}

void pqcrystals_dilithium_3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln180_fu_225_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln137_fu_328_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(icmp_ln180_1_fu_363_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(icmp_ln87_fu_467_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

}

